src/freenet/client/async/BaseManifestPutter.java
src/freenet/client/async/ContainerInserter.java
src/freenet/support/api/ManifestElement.java

Sharewiki and Freereader work again.
→ old: http://127.0.0.1:8888/KeyUtils/Site/?mftype=TARmanifest&key=SSK@pFAHc9wpvLztZ4hYor2qYH54lYTYF6j6Pbg6Mqy5-bM,SPN7S~kYzaggMCCavc46mBxsrI5gTrtcc5JP4aXCTtg,AQACAAE/Test-1&hexwidth=32&deep=checked
→ new: http://127.0.0.1:8888/KeyUtils/Site/?mftype=TARmanifest&key=SSK@pFAHc9wpvLztZ4hYor2qYH54lYTYF6j6Pbg6Mqy5-bM,SPN7S~kYzaggMCCavc46mBxsrI5gTrtcc5JP4aXCTtg,AQACAAE/Test-3&hexwidth=32&deep=checked
This still needs someone who managed to setup junit4 to check whether all tests run.
Fixes bug 0006385 and bug 0006446:
- https://bugs.freenetproject.org/view.php?id=6385
- https://bugs.freenetproject.org/view.php?id=6446

Manifest putter fix mime type guessing

---

src/freenet/clients/http/BookmarkEditorToadlet.java
src/freenet/clients/http/ConnectionsToadlet.java
src/freenet/clients/http/QueueToadlet.java
src/freenet/clients/http/WelcomeToadlet.java
src/freenet/clients/http/staticfiles/js/checkall.js

This adds a feature I wanted to have for months: Just select all my friends with a single click.
A nice improvement would be to have a central place for the Javascript, but I’m not sure where to put that.
I’m working on adding the select-all logic for the queue, too. But I think it should ideally be in all tables which have check boxes on each line: click the box in the header to check or uncheck all boxes.

Checkbox: select all friends

---

src/freenet/clients/http/StartupToadlet.java

Node startup can be much faster than 20 seconds, so to retain
responsiveness, especially when waiting on the first run setup, a faster
response rate is preferable.

Reduce startup page refresh period to 1 second

---

src/freenet/client/HighLevelSimpleClientImpl.java

Fixes a leak in HLSC.insertRedirect(), used occasionally by Library on Spider inserts.

Fix another leak

---

src/freenet/clients/http/WelcomeToadlet.java

I kept the switch code inside to allow for easily re-adding this in case library should work well again (since we want to have a working search box again).
I used spaces for indentation - should I switch to tabs for consistency or keep spaces because that’s what we want to have in future?
If we have no other pull-requests against the WelcomeToadlet, I could also reindent the whole file.
Caveat: Library does not load for me at all, so I cannot test whether the search box gets shown correctly. For that we’d need a Library plugin which works with purge-db4o.

hide the no-library warning.

---

.classpath

Fix classpath for Eclipse. The new build process requires the file in this location for ant anyway, so it should be the same in Eclipse.

Fix classpath for Eclipse

---

src/freenet/client/async/SplitFileFetcherStorage.java
src/freenet/client/async/SplitFileInserterSender.java
src/freenet/client/async/SplitFileInserterStorage.java

Fix a serious bug in the new client layer causing completed inserts (and possibly requests too) to not get removed from the internal queue structures (RGAs) and thus prevent other inserts from running. This is the minimal version of the fix. However the other one may make more sense given that the locking is pretty tricky either way. Please review with care; this one is much shorter!
It is important that this goes in for 1468, i.e. before purge-db4o is public.

Fix broken splitfile wakeup times

---

test/freenet/client/async/SplitFileInserterStorageTest.java

Assert is bogus. The callback is called from a thread on the executor, which
might or might not have actually exited at this point. Does not affect the
other 2 assertions, which should both definitely be true; the first one is
the crucial bit, we don't get the actual failure until after the encode has
completed, but then we get a failure and not an encoded notice.

Fix another unit test race condition.

---

src/freenet/client/async/SplitFileFetcher.java
src/freenet/client/async/SplitFileInserter.java

Fixes the underlying bug that put me onto #351. However that is still valid, as we should implement the contract.
Testing procedure: (Appears to be working)
- Start a node *without* #351 but with this patch (cherry-pick it).
- Start a bunch of inserts at priority 3 and a bunch at priority 4.
- After the inserts at 3 finish, the inserts at 4 should proceed.
- Without this patch, this does not happen. At least sometimes it doesn't. That's what put me on to #351...

Fix not unregistering inserts

---

src/freenet/client/async/SplitFileFetcherStorage.java
src/freenet/client/async/SplitFileInserterStorage.java
src/freenet/support/RandomArrayIterator.java
test/freenet/support/RandomArrayIteratorTest.java

This rewrites `chooseBlock` to be functionally equivalent to the existing code, but linear in worst case complexity in terms of number of segments (as compared to non-terminating previously). In the most common case, where (almost) all segments yield blocks, this method maintains O(1) complexity.
The primary feature of this pull request is to replace the following line, which is obviously non-terminating in the worst case (although such an infinite run happens with zero probability):
```java
while(tried[segNo = random.nextInt(segments.length)]);
```
Additional costs in memory are insignificant: they are limited to one integer per segment to maintain a permutation of segment array indices to shuffle.

Linear complexity bounds on SplitFileInserterStorage.chooseBlock / SplitFileFetcherStorage.chooseRandomKey

---

src/freenet/node/PeerNode.java

This bug has been present since introduction of different backoff types in 2008.
See commit: 514b85cb197777345c451342b33dd2f85b20747f

Fix: Transfer backoff was never being reset.

---

src/freenet/pluginmanager/OfficialPlugins.java

build0014 includes a huge amount of work: fixes bugs, updates for
purge-db4o, and adds an event-based API. build0015 is a small build and
tests fix on top of it - it makes no functional changes. The minimum
version is set to it because earlier versions will be broken with
purge-db4o.

Update WebOfTrust to build0015

---

src/freenet/node/Announcer.java

When starting a new node without seednodes, Fred gives a warning about the missing seednodes in the web interface but never tries again to find them, so that even if you download the seednodes into the node directory you have to restart the node in order for it to find the seednodes.

Try to reload seednodes if they are missing

---

src/freenet/support/TransferThread.java

Reasons are explained in the added JavaDoc.
(For completeness, it shall be noted that the fixed version in WOT which the JavaDoc talks about is not committed yet. However there is a bugtracker entry at WOT which documents that it needs to be done, and it is the immediate next entry on my TODO list, so IMHO we can deprecate this already to make sure that people don't run into the bugs)

freenet.support.TransferThread: Deprecate

---

src/freenet/support/io/SwitchableProxyRandomAccessBuffer.java
src/freenet/support/io/TempBucketFactory.java

When a temp RAF is closed we need to close the bucket as well to avoid a leak warning. But this is more complicated than it at first appears! Clarifies related code and improves things a bit.

Fix leak warnings and temp buckets/buffers (second attempt)

---

src/freenet/clients/fcp/ClientPut.java

Just something I noticed while perusing `ClientPut`’s source code in order to clear up something that looks fishy on the wiki.

Fix potential resource leak

---

src/freenet/client/async/SplitFileFetcherCrossSegmentStorage.java
src/freenet/client/async/SplitFileFetcherSegmentStorage.java
src/freenet/client/async/SplitFileFetcherStorage.java
src/freenet/client/async/SplitFileInserter.java
src/freenet/client/async/SplitFileInserterCrossSegmentStorage.java
src/freenet/client/async/SplitFileInserterSegmentStorage.java
src/freenet/client/async/SplitFileInserterStorage.java
src/freenet/client/async/SplitFileInserterStorageCallback.java
src/freenet/node/NodeClientCore.java
src/freenet/support/MemoryLimitedJob.java
src/freenet/support/MemoryLimitedJobRunner.java
test/freenet/client/async/ClientRequestSelectorTest.java
test/freenet/client/async/SplitFileFetcherStorageTest.java
test/freenet/client/async/SplitFileInserterStorageTest.java
test/freenet/support/MemoryLimitedJobRunnerTest.java

Priorities for MemoryLimitedJob's, i.e. FEC decode/encode jobs. Please check the call stack to ensure that there are no locking issues, but there shouldn't be any.
This should ensure that fproxy is reasonably responsive even when there are big files completing, and mitigate the damage caused by BC < 1.52 with encrypted disk enabled.

Prioritise memory jobs

---

src/freenet/crypt/MessageAuthCode.java
test/freenet/crypt/MessageAuthCodeTest.java

This fixes the test failures discussed [on devl](https://emu.freenetproject.org/pipermail/devl/2015-August/038145.html) by preventing `MessageAuthCode.verify()` from throwing when given `null`. Is this an appropriate way to go about it? I didn't find any callers where this would change behaviour.

MessageAuthCode: fix JVM-version-dependent test failure

---

src/freenet/clients/fcp/ClientGet.java
src/freenet/clients/fcp/ClientPutBase.java
src/freenet/clients/fcp/ClientRequest.java
src/freenet/clients/fcp/EndListPersistentRequestsMessage.java
src/freenet/clients/fcp/FCPMessage.java
src/freenet/clients/fcp/GetRequestStatusMessage.java
src/freenet/clients/fcp/ListPersistentRequestsMessage.java
src/freenet/clients/fcp/PersistentRequestClient.java

I’m currently writing a new high-level FCP client implementation and I’m facing a problem with processing the various replies to a `ListPersistentRequests`. Usually, when I send an Identifier with a request, the response carries the same Identifier; associating one with the other is a breeze. However, the replies to a `ListPersistentRequests` all have their own identifiers so it is impossible to associate the replies with a request. Using the approach of “use everything until you get an `EndListPersistentRequests`” will only work if all replies to a `ListPersistentRequests` are sent atomically. Unless that is guaranteed, a second `ListPersistentRequests` on the same connection will happily interleave its replies with the replies to the first request. Madness will ensue.
This pull request …

Add request identifiers to persistent requests

---

NEWS

The goal of the NEWS file is to distribute the effort of gathering and summarizing noteworthy changes.
Ideally writing release notes would only consist of turning the list of changes into a sentence (adding “this release” and a few *and*’s and *also*’s).

add a NEWS file

---

src/freenet/node/Announcer.java
src/freenet/node/DarknetPeerNode.java
src/freenet/node/FNPPacketMangler.java
src/freenet/node/Node.java
src/freenet/node/OpennetManager.java
src/freenet/node/OpennetPeerNode.java
src/freenet/node/PeerManager.java
src/freenet/node/PeerNode.java
src/freenet/node/SeedClientPeerNode.java
src/freenet/node/SeedServerPeerNode.java
src/freenet/node/SeedServerTestPeerNode.java

Slightly larger cleanups, mostly organised around "PeerNode constructor takes too many arguments". Some minor performance gain on seednodes.

Cleanup peernode

---

.classpath

The previous sourcepath was uppercase, while our contrib repository uses a lowercase name:
https://github.com/freenet/contrib
If people clone it, they will get a "contrib" directory, not "Contrib" as the previous sourcepath used.
This commit changes the sourcepath to be lowercase just like the repository name.
This fixes Eclipse to find the db4o source code automatically as long as people clone "fred" and "contrib" into the root directory of their workspace. This is useful for Web of Trust and Freetalk developers: Eclipse will be able to display db4o JavaDoc now.

Eclipe classpath: Fix sourcepath of contrib to match repository name

---

src/freenet/clients/http/staticfiles/base.css
src/freenet/clients/http/staticfiles/themes/boxed/layout.css
src/freenet/clients/http/staticfiles/themes/grayandblue/layout.css

This overly broad directive caused headers in fniki and FlogHelper
previews to appear as normal text.
The only place Fred uses headers is page titles, so this moves its
styling to a selector specific to it.

themes: avoid styling headers as normal text

---

NEWS.md
src/freenet/clients/http/BookmarkEditorToadlet.java
src/freenet/clients/http/bookmark/BookmarkItem.java

_xiaoyu on IRC reported problems using blank bookmark names. When a bookmark with a blank name was added, it could not be navigated to but did not cause other problems. After restart when parsing the blank name the bookmark state became malformed somehow and prevented any operations on the list of bookmarks. These changes do two main things:
* Disallow new bookmarks with blank names to prevent the problem from occurring anew.
* Load bookmarks with blank names as "Unnamed Bookmark" to fix the problem where it was already occurring.
I'm not certain this is the best way to go about it because [existing code](https://github.com/freenet/fred/blob/caba7734a583aafc55ebe229a270f3a70eed1876/src/freenet/clients/http/bookmark/BookmarkItem.java#L60) seems like it was at least intended to [do that …

Disallow blank bookmark names

---

src/freenet/support/RandomGrabArray.java

Please consider for the next-but-one build. And test!!!
(Thanks for bertm for finding this problem, and for contributing some additional cleanup)
RGA.wakeupTime was always 0. Functionally this should not have any great
impact, although clearly the code was wrong.
SRGA.removeRandomExhaustive calls getWakeupTime and then if that returns 0
(indicating not in cooldown), it calls RGA.removeRandom. Which will then
return a positive cooldown time if it's actually in cooldown - so SRGA will
set itself into cooldown on the basis of that value. We were always returning
0 from RGA.getWakeupTime(); this fixes that, which should speed up SRGA
slightly.
There could be a correctness issue if reduceWakeupTime is being called a lot.
Currently IIRC we call clearWakeupTime instead in the common case where a …

Fix RGA.wakeupTime never getting set.

---

src/freenet/client/filter/HTMLFilter.java

This fixes an obvious typo in HTMLFilter that prevented `<input type="reset">`-style form elements from passing the filter.

HTMLFilter: fix processing of reset input element

---

src/freenet/node/Node.java

Not found SSKs were always being logged as found in cache.

Fix improper indenting & logging bug caused by it

---

src/freenet/support/compress/RealCompressor.java
src/freenet/support/io/NativeThread.java

This is something I've introduced in 7487c51c32e673bde5e89a148b449179d8fc53b8

Fix bug #6623 : Wrapper.log: Lots of "setNativePriority(X) has failed!"

---

src/freenet/support/JVMVersion.java
test/freenet/support/JVMVersionTest.java

We now properly parse JVM version numbers, instead of comparing them
lexicographically.
This resolves bug [6390](https://bugs.freenetproject.org/view.php?id=6390).

Fix JVM version comparison for version >1.9 and build >99

---

src/freenet/node/updater/NodeUpdateManager.java

As discussed on bug #4490 and
https://emu.freenetproject.org/pipermail/devl/2015-November/038581.html
This implements the minimum required for next release.

Only update essential plugins if we have to

---

.travis.yml
test/freenet/support/JVMVersionTest.java

Setup Travis at https://travis-ci.org/freenet/fred/
... It highlights that #437 uses Java7-only Integer.compare(int, int); thanks @Bombe  for noticing!

Setup Travis at https://travis-ci.org/freenet/fred/

---

src/freenet/node/FNPPacketMangler.java
src/freenet/node/PeerManager.java
src/freenet/node/PeerNode.java

Fixes a bug nextgens missed in #440 and cleans up slightly. 
**Please consider for 1471** because the bug affected announcement performance: Checking for peers we had already announced to failed because we were putting ECDSA pubkey hashes into the exclude set, but then comparing them against obfuscation keys (PeerNode.identity).

FNP fixes post 440

---

test/freenet/l10n/BaseL10nTest.java

On Java 6 the classloader path may return multiple colon-delimited paths, which makes using the classloader path not work as intended. Using the class path requires more backing out of the build directory.
In my testing this allows the tests from #421 to pass under Java 6, but I really hope there's a more idiomatic / less fragile way to do this.

test: fix resource path on Java 6

---

src/freenet/store/caching/CachingFreenetStoreTracker.java

Fixes a nasty race condition which could happen with late initialisation
of the client-cache (e.g. due to password encryption), would cause an
infinite loop.
Please consider for 1471 (as this fixes a regression in next).

Re-check the stores list periodically

---

src/freenet/node/NodeDispatcher.java

We send a rejection, so clearly we do claim the message. We don't want it to be reconsidered later. The message is "leaked" into the unmatched messages buffer, thus wasting both memory and CPU (but it will eventually be dropped due to limits). Low priority but trivial fix.

Fix leaking a message when rejecting because not routable

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

next is too generous with CSS selectors in nav-*. I doubt that this is exploitable but we should not allow more than the spec unless there is a good reason. Also, we don't sanitize/rebuild the selectors here (which we do in other cases), which might make any possible exploit easier.
To be clear, this should be considered for 1471 since it's a possible (but unlikely) security regression in next/pre-1471 relative to 1470.

Fix CSS filter being more generous than it should be in 1471-pre

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

A few minor fixes to the CSS changes. Removes some keywords that shouldn't be allowed, adds some that should. Can wait.

CSS: more 1471 fixes

---

src/freenet/crypt/HMAC.java
src/freenet/node/DatabaseKey.java
src/freenet/node/FNPPacketMangler.java
src/freenet/node/NewPacketFormat.java
src/freenet/node/PeerNode.java
test/freenet/crypt/HMACTest.java
test/freenet/crypt/HMAC_legacy.java

Odds are it won't make the code any faster... but it's more readable and might be better equipped than us to deal with side channels.
It's a lot less ambitious than #258

Replace our HMAC implementation by whatever JCA provides

---

src/freenet/node/updater/NodeUpdateManager.java

I'm posting this for review as requested but have yet to test it. As Matthew said previously:
> The resulting UOM should be tested to work with {windows, linux} * {old to new, new to new} * {ordinary fetch, UOM}.
I don't know if I'm going to bother to test {Windows, Linux} because the fetching doesn't differ between the two.

updater: change old update key to new for Java 7+

---

test/freenet/client/async/SplitFileInserterStorageTest.java

This changes some large in-memory buffers to on-disk buffers to avoid
OOM unit test failures on Travis CI.

Reduce memory usage of SplitFileInserterStorageTest

---

src/freenet/node/NodeDispatcher.java

As a result of [commit f3e3be4](https://github.com/freenet/fred/commit/f3e3be45698272db462ae45f784ff4049c692e92), messages received from an unroutable source may be claimed as matched although they actually weren't rejected or otherwise processed. This behavior led to the failure of noderef-transmissions from seed nodes to a new opennet node, if the first transfer message arrived before the corresponding receiver thread started. This commit ensures that unhandled messages are kept marked as unmatched.

Avoid claiming of unrejected messages by NodeDispatcher

---

src/freenet/clients/fcp/FCPServer.java
src/freenet/clients/http/SymlinkerToadlet.java
src/freenet/config/Config.java
src/freenet/config/SubConfig.java
src/freenet/node/Node.java
src/freenet/node/NodeStarter.java
src/freenet/node/RequestStarterGroup.java
src/freenet/node/SecurityLevels.java
src/freenet/node/TextModeClientInterfaceServer.java
src/freenet/node/updater/NodeUpdateManager.java
src/freenet/pluginmanager/PluginInfoWrapper.java
src/freenet/pluginmanager/PluginManager.java
test/freenet/config/ConfigTest.java

This makes it easier to mock configs and subconfigs once we
get around to unit testing.

Remove direct calls to SubConfig constructor

---

src/freenet/node/PeerNode.java

PeerNode previously failed to increment in/out traffic statistics
since startup, and did not initialize the total counters to include
the counts from prior Freenet sessions. The counters intended to
count the in/out traffic statistics since startup were initialized
to the total count and never incremented. This means that the two
sets of counters were reversed from their named purpose. This patch
fixes this and changes the total counters into totals at startup time.
The all time total traffic can be calculated as the sum of the traffic
since startup and the traffic before startup. No external code is aware
of this internal bookkeeping change, but it eliminates the need to
actively maintain both counters during runtime.

Fix peer node network traffic statistics

---

src/freenet/node/Announcer.java

Always log errors when we fail to parse the seednodes file. If we fail
on one entry, now read to the end of the line and proceed parsing
instead of bailing out prematurely.

Make seednodes.fref parsing more robust

---

src/freenet/clients/http/ConnectionsToadlet.java
src/freenet/clients/http/DarknetAddRefToadlet.java
src/freenet/node/Announcer.java
src/freenet/node/NodeFile.java
src/freenet/node/simulator/SeednodePingTest.java
src/freenet/node/updater/NodeUpdateManager.java

seednodes.fref is read from the nodeDir by the Announcer, so we should
store it there as well when we fetch the current version.
This should fix bug 6684.
To prevent future confusion, this adds a central registry for node-
managed files and their locations. This initially contains only the
locations of the files updated by NodeUpdateManager, but may later
be reused for other purposes.

Store updated seednodes.fref in nodeDir, not userDir

---

src/freenet/node/MultiMessageCallback.java

If message.sent() is called before cb.arm(), then we only call cb.sent() after completion. We should call it on arm()ing. This probably only affects simulations, but possibly also very busy nodes.
This is a minor accounting glitch, low priority, but might conceivably caused forced disconnects.

Fix race condition in MultiMessageCallback

---

src/freenet/client/async/BinaryBlobWriter.java
src/freenet/clients/fcp/ClientGet.java

This is based on #495 and creates the bucket in makeGetter() instead of at two of its callers. It works in my testing - I get hangs when fetching blobs on 1472 where it only writes what seems to be a header to disk. With these changes applied I get a much larger blob back.
00000000  6d 58 24 9f 72 d6 7e d9  00 00 00 00 00 00 00 02  |mX$.r.~.........|
00000010  00 00                                             |..|
00000012

Fix fcp blob downloading

---

src/freenet/node/RequestSender.java

This should improve protection against local attackers. I would like it to be considered for 1472 if not earlier. The performance impact should be marginal: Path folding does not block returning the data, although maybe we might end up running slightly fewer requests as a result. If so increasing the limits (BANDWIDTH_LIABILITY_*) in NodeStats would be a simple solution.

Random delay for opennet ack when not path folding (locally)

---

src/freenet/clients/http/QueueToadlet.java

This fixes a regression introduced in
c11c5a93a7299eb63c2b1110e07df694bddaf04c (#513) that lead to the absence of
the priority buttons and presence of the restart button, for all
uncompleted uploads.

Fix uncompleted uploads being treated as failed in queue

---

src/freenet/node/Node.java

I think this should have been the behaviour all along to allow us to upgrade the network to new internet connection requirements without continuously killing old nodes.
I cannot just re-use the checking function, because that must throw an exception for the config settings.

FIX: on too low bandwidth, use min bandwidth

---

src/freenet/clients/http/wizardsteps/BANDWIDTH_MONTHLY.java

I changed the scheme to not rely on the absolute value of the min bandwidth, so it does not break again when we adjust the min bandwidth.

fixed bandwidth selection per month

---

.classpath

When compiling plugin-WebOfTrust, I noticed a weirdness which shows that
the previous source code path for db4o is wrong:
I changed a function ```foo(ObjectSet<Thing> x)``` to have the signature
```foo(List<Thing> x)```. The compiler did *not* complain when passing
```ObjectSet<Thing>``` to the function which expects a ```List```. So this shows
that class ```ObjectSet<T>``` as we ship it in freenet-ext.jar v29 does
implement ```List<T>```. This can also be shown by unpacking the jar and
running the Java disassembler:
```
$ javap ObjectSet.class
...
public interface com.db4o.ObjectSet<Item> extends
java.util.List<Item>, java.util.Iterator<Item> {
```
Yet when browsing the source code as the previous classpath specified
it, the ObjectSet there does **NOT** implement ```List<T>```.
So what …

Eclipse config: Fix source path of db4o in freenet-ext

---

.settings/org.eclipse.jdt.core.prefs

= Set to Java 7.
The date stamp was removed by Eclipse automatically. I think that makes sense, the file was modified more recently now.

Eclipse config: Fix compiler Java version to match Ant builder

---

src/freenet/client/async/ClientRequestSelector.java
src/freenet/node/RequestStarter.java

This was planned long ago but apparently never implemented. It should make cooldown requests more reliable, and removes the need for the arbitrary wait(1000) in RequestStarter. It may also make #524 viable, or something more ambitious and less ugly.

Cooldown fixes

---

src/freenet/node/NodeStarter.java
test/freenet/node/NodeAndClientLayerBlobTest.java
test/freenet/node/NodeAndClientLayerTest.java
test/freenet/node/NodeAndClientLayerTestBase.java

Adds basic unit tests for the client layer when run on a single node (i.e. insert/request to datastore), including binary blobs (the data is fetched on a second node using the blob). These tests only run when -Dtest.extensive=true.

Test node blobs

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

This goes a bit further than #445. It documents the syntax and limitations and also fixes some potentially confusing bugs in future parsing rules. It is not urgent. CSS tests pass.

CSS parser expression fixes

---

src/freenet/clients/http/PproxyToadlet.java
src/freenet/l10n/freenet.l10n.en.properties

Added a warning that files stored by a plugin are not removed when the plugin is unloaded, as requested in bug 6558. I didn't add the FredPluginWithUninstallation interface, because it doesn't make sense until we have functionality for it.

Add warning message about leftover plugin files

---

src/freenet/client/filter/HTMLFilter.java

We have an mp3 filter and current browsers support mp3 in the audio-tag, so this provides actual capabilities to users.
The mp3 filter might be too strict (it butchers my test file), but that’s a separate fix.

filter: add minimal support for audio tag

---

src/freenet/clients/fcp/PluginInfoMessage.java

Thanks to @Bombe for discovering this!
See https://github.com/freenet/fred/pull/319 for details about the new API, including statements about the compatibility.

PluginInfoMessage: Fix wrong "does not provide FCP" info about plugins

---

build.properties

One regular workflow of using deprecation in fred is:
- A new version of Java appears and allows us to replace custom
code with Java API.
- The volunteer who discovers this does not have the time or knowledge
to replace all usages of the custom code immediately.
For an example of these difficulties, see the commit messages of the
two commits which this PR highlights in its message:
https://github.com/freenet/fred/pull/541
- So we instead deprecate our custom API, and wait "some time" before a
developer comes along who is capable of replacing all usages of it.
As we really don't have enough developers, "some time" is usually years.
So overall, there will be some deprecated things in fred at any time.
Thus we'd constantly have compiler warnings about usage of deprecated API which we cannot …

Ant builder: Reduce warnings about usage of deprecated API

---

src/freenet/node/useralerts/JVMVersionAlert.java
src/freenet/support/JVMVersion.java
test/freenet/support/JVMVersionTest.java

Odds are we won't require java8 before it's in debian stable...
and it won't be before stretch is released (freeze is scheduled for 02/2017)

Warn users that java1.7 is EOL

---

src/freenet/client/async/KeyListenerTracker.java

These are the slightly riskier changes originally included in the Frostbite fix, that were left out to allow for earlier adoption.
The addition of try/catch constructs introduces a lot of duplicate
code around `probablyWantKey` matching. These changes factor out this matching
and perform some additional cleanup.
Checks for duplicate or null elements in `keyListeners` are removed:
`addKeyListener` ensures there are no such duplicates. As an additional
layer of assurance, make the `keyListeners` member private.

Cleanup KeyListenerTracker

---

src/freenet/node/NodeStats.java

Just some minor deduplication of code.
Mind that the assertion `assert(loc > 0 && loc < 1.0);` has been changed to `assert(loc >= 0 && loc < 1.0);`, zero *is* a valid location after all.

NodeStats: reduce code duplication in request location tracking

---

src/freenet/node/AnnounceSender.java
src/freenet/node/BaseSender.java
src/freenet/node/DarknetPeerNode.java
src/freenet/node/Node.java
src/freenet/node/OpennetPeerNode.java
src/freenet/node/PeerManager.java
src/freenet/node/PeerNode.java
src/freenet/node/SeedClientPeerNode.java
src/freenet/node/SeedServerPeerNode.java

This is less invasive than #564 and probably a good idea.
We don't want to land a request far from the target just because it has a peer that's closer to our current location!
Please ACK it; I'm not sure whether the callers setting HTL at silly values should be changed.

Don't use FOAF if HTL<2

---

src/freenet/support/JVMVersion.java
test/freenet/support/JVMVersionTest.java

This fixes bug [6862](https://bugs.freenetproject.org/view.php?id=6862) by parsing less strictly.

Fix parsing of Java versions >= 9 (JEP-223)

---

src/freenet/clients/http/SessionManager.java

`previousTime` was never written, so this check was useless and would never fail.
These kind of checks belong in a unit test, not in production code.

SessionManager: remove dead sanity check

---

src/freenet/support/SparseBitmap.java
test/freenet/support/SparseBitmapTest.java

Use the logarithmic querying methods TreeSet has to offer, instead of iterating over the complete set for each query.
Most importantly, this greatly reduces the complexity of `notOverlapping` for larger ranges.
Some additional testing code is added for increased confidence in the correctness.

Improve SparseBitmap efficiency

---

test/freenet/support/MemoryLimitedJobRunnerTest.java

With high thread counts on some systems this can intermittently result in the JVM hitting a thread count limit and being unable to create another thread.
That said, what thread limit is this, where is it set, and can the test ensure it is high enough before starting? xor recommended breaking on OOM in a debugger and checking if the thread count really is high.

MemoryLimitedJobRunnerTest: avoid high thread counts

---

src/freenet/clients/fcp/FCPMessage.java
test/freenet/clients/fcp/FCPMessageTest.java

This fixes `AllData` and all other data-carrying messages that are sent as a response to `ListPersistentRequests`.

Fix wrapped FCP message

---

src/freenet/store/saltedhash/SaltedHashFreenetStore.java
src/freenet/support/WrapperKeepalive.java
src/freenet/support/io/Fallocate.java
src/freenet/support/io/PooledFileRandomAccessBuffer.java

It turns out that some old libc will rewrite calls from
fallocate() to posix_fallocate() ... and this might take
a while depending on the FS.
We need to ensure that regardless of the situation,
the wrapper doesn't kill the node.

Fix a potential problem with fallocate()

---

src/freenet/store/saltedhash/SaltedHashFreenetStore.java
src/freenet/support/io/Fallocate.java
src/freenet/support/io/PooledFileRandomAccessBuffer.java

This should deal with https://gist.githubusercontent.com/xor-freenet/18027234f1849531f17e84f62056086c/raw/62a39f65c53555bda0d6f37788d80cde9a8ff447/fred-failure.txt as mentioned in #585

Handle EOPNOTSUP

---

src/freenet/pluginmanager/PluginManager.java

... instead of just the message of the exception.
This will ease support a lot as the messages have turned out to be worthless usually, we often needed to ask people to dig through the logs for the stack trace.

FProxy: If a plugin throws during startup then show the stack trace

---

src/freenet/support/codeshortification/IfNull.java

Fred does not use these, they were added for plugins.
So let's deprecate them for a while before we remove them.

Class IfNull: Deprecate in favor of Java 7 providing the same

---

src/freenet/clients/fcp/GetRequestStatusMessage.java

The “listRequestIdentifier” parameter should only be used when sending
messages as a response to a “ListPersistentRequest” command. When using
“GetRequestStatus,” this identifier would only duplicate the
“Identifier” field and is thus not necessary.

Don’t send unwanted list request identifiers

---

src/freenet/clients/fcp/ClientGet.java
src/freenet/clients/fcp/ClientPutBase.java
src/freenet/clients/fcp/ClientRequest.java
src/freenet/clients/fcp/GetRequestStatusMessage.java
src/freenet/clients/fcp/PersistentRequestClient.java

The “includePersistentRequest” parameter was always `true`.

Remove unused parameter

---

test/freenet/support/TimeUtilTest.java

Testing this because WoT assumes it to be correct so it can use it as foundation for unit tests of further Date manipulation functions.

TimeUtilTest: Test setTimeToZero()

---

src/freenet/node/Node.java
src/freenet/node/updater/NodeUpdateManager.java
src/freenet/node/useralerts/JVMVersionAlert.java
src/freenet/support/JVMVersion.java
test/freenet/support/JVMVersionTest.java

When the too-old version was advanced to 1.8 in 465cf7391d9f11fb05b2dea8f6cf382d5b714d6f it caused new installs on Java 7 to begin checking the legacy Java 6 update URI, despite only being intended to change the EoL alert. This introduces a distinction between a version old enough to display an alert, and a version old enough to use the legacy update URI.
I have not yet tested a node with these changes, but I did run into the problem when resetting my node's updater settings page to defaults while using Java 7.

JVMVersion: add distinction between EoL alert and updater

---

src/freenet/node/PeerManager.java

Recently failed is one of the great annoyances when using Freenet, so I think it would be great to merge and use this.
The change likely makes it cheaper to create load by firing requests which never finish, but given that recently failed hits me at least once a week, I think this change should go in (I checked the diff and it looks sane).

Much less recentlyfailed

---

src/freenet/clients/http/BookmarkEditorToadlet.java
src/freenet/clients/http/bookmark/BookmarkItem.java
src/freenet/clients/http/bookmark/BookmarkManager.java

Previously, if you received a notification about an updated USK bookmark, and then restarted the node, the notification would be lost: The node stored the updated edition number to disk, but not the notification. So it wouldn't download the edition again, and thus not create another notification.
This is fixed by this PR.
_Please use this PR message as message of the merge commit._

Persist "Bookmark Updated" notifications across restarts

---

build.gradle
src/freenet/support/ProcessPriority.java

As discussed on IRC a few weeks ago, the ProcessPriority class is currently using JNA direct mapping (`Native.register()`) on Windows, Linux, and Mac, but this causes a segfault on 64-bit Windows.
Some other projects have noticed that rolling back the JNA version "fixes" the issue without any changes to the code. It might or might not be a JNA bug, but it works properly on the current JNA version if we use JNA interface mapping instead with the correct native types, `DWORD` and `HANDLE` from `jna-platform`. 
Interface mapping is apparently slower, but that should be OK here as it is only used once during the life of the process.
The exception refers to an invalid calling convention `63`,  but that's likely not the real issue. `63` is just a constant that means `stdcall`, and 64-bit …

Use JNA interface mapping in ProcessPriority on 64-bit Windows

---

src/freenet/client/InsertException.java
src/freenet/client/async/BaseClientGetter.java
src/freenet/client/async/BaseClientPutter.java
src/freenet/client/async/ClientGetter.java
src/freenet/client/async/ClientPutter.java
src/freenet/client/async/ClientRequester.java
src/freenet/client/async/ManifestPutter.java
src/freenet/client/async/SingleFileInserter.java
src/freenet/clients/fcp/FinishedCompressionMessage.java
src/freenet/clients/fcp/PutFailedMessage.java
src/freenet/support/io/ReadOnlyFileSliceBucket.java

db4o support has been removed by nextgens recently. For some reason, he left some constructors which were labeled as "zero arg c'tor for db4o on jamvm".
Commit d0c1d9f60376335d4cdb5c8b64bd2b7357129383 removes the ones which can be removed. Unfortunately that is not all of them:
While reading related code, I saw that there are similar constructors which were labeled as "For serialization", you can see them in my commit 47c45addd5618c4bc0759a214de473bd20b31653 (which deals with their lack of JavaDoc formatting as a bonus fix). They were added when replacing db4o with Java serialization at toad's commit 10b1d664860f0a74b02e57ba2dc6edbf77cae521. This made me realize that some of the "zero arg c'tor for db4o on jamvm" are probably still needed:
They are protected, not private, just like the …

Remove db4o constructors; fix wrong documentation of repurposed ones

---

src/freenet/config/WrapperConfig.java

Previous patch fixed open/read, but write was still broken.
This patch includes write, and worksforme (actually run-tested it this time).   From what I'm seeing online, java has turned / in paths into whatever is the appropriate separator char for decades, and should pose no problems.  Hard coding \\ is what you want to avoid.

fix memory limit setting on windows v2

---

src/freenet/clients/http/wizardsteps/BANDWIDTH_MONTHLY.java
src/freenet/node/Node.java
src/freenet/node/OpennetManager.java

This is one of two options I see for reducing the required peer count per bandwidth.
I see it as important, because current versions of Freenet have difficulty keeping more than 70 connections, so users with high bandwidth have flapping connections, which will stop convergence of the network.
This is the more risky option: reducing the minimum bandwidth back down to 5KiB and allowing the peers to go down to 4 — one long connection and 3 short ones. With this change, very slow nodes should contribute to routing roughly as much (or as little) as they did with 10 connections before the link length fix.
On the other hand, with this change, slow nodes should easily be able to keep all their connections.

adjust bw limit: min peers 4 and min bandwidth 5KiB/s (more risky option)

---

src/freenet/node/updater/NodeUpdateManager.java
src/freenet/node/updater/UpdateOverMandatoryManager.java
src/freenet/support/JVMVersion.java
test/freenet/support/JVMVersionTest.java

This rekeys URIs for both EoL and newer versions of Java, which is not supported by existing code. This separates the legacy URI - for EoL JVMs going forward - from the "previous URI."
Once this is reviewed and ready to merge I can distribute the private keys before merging if that seems preferable.
I tested that the key config updated as expected, but not UOM. It behaves as expected when first running Java 7, subsequently running Java 8, and first running Java 8. (The script I used, which is specific to Arch, is [here](https://gist.github.com/Thynix/8d6f1ff2526dc83d25184d8dfb48bb6b).)

Rekey the update URIs to ensure they are RFC6979

---

src/freenet/clients/http/SimpleToadletServer.java

This change should make fproxy use the default theme as starting theme; which is sky-static.
sky-static is much nicer to use than clean-dropdown, but still not Winterfacey level. But its CSS is optimized for faster load times.
The switch to sky-static as default already happened Oct 20, 2015, but did not have an effect because of the override this commit removes.

fix: switch to theme sky static had not worked

---

build.gradle

previously the created jar-file would not have run with Java 7, because the compatibility mode was only set on the javaVersion task. To test:
javap -verbose -classpath build/classes/java/main freenet.client.async.DownloadCache | grep major

gradle: apply compatibility mode to all classes, not just to Version.java

---

src/freenet/crypt/KeyGenUtils.java

Fix issue with BounceCastleProvider introduced in abad64d133ed9a674d5f666f48db178a85652b9e causing node shutdown with OOM error.
It was opted to use a static initialization method to setup provider using the `static` initializer.
I've a node running on this branch and it seems to be OK following the reproduction steps provided in the mailing list.

[PATCH] Fix memory leak with BouncyCastleProvider

---

src/freenet/client/async/SplitFileFetcher.java
src/freenet/support/io/BaseFileBucket.java

The reverted change made Freenet fail under Windows 8.1, as reported in FMS:
> TS-Pi@8kCqlpKwsXackbaIm7PI71gTfgRzZZScud4qfg8qcEU wrote :
>> dark_mater@aiiPp9iU6YYQprBhtmTW4QpXU6OUh-EOb6eThYhmmqs wrote :
>>> The lastest version of freenet is barely functional on windows 8.1 (see disclaimer at end). The problem is that java is not able to either see or edit the hidden files (AKA dot-files). One can surf websites if they load quickly but browsing is slow due to frequent restarts and the inability to download anything via the freenet web proxy, that takes longer to download then the time before freenet crashes/resets. 
>>> 
>>> It might be usable with external download tools such as Thaw but regardless the preformance will be poor. 
>>> 
>>> I don't know if anyone else has experienced simmiar …

Revert hiding tempfiles

---

src/freenet/node/OpennetManager.java
src/freenet/node/UIDTag.java

This is an emergency fix because some of our users with the biggest bandwidth report big problems with CPU load. They report that the update from 1480 to 1481 increased their CPU load by factor 2 to factor 3. Since in the merge from master to merge we kept the min bandwidth requirements of 10kB/s, the lowest peer count will be 4, which still suffices for scaling (as shown by the link length fix).
Risk: Users might complain that their target peers are reduced, because they don’t understand that this does not reduce the bandwidth they can use (because the bandwidth per peer is increased if the peer-count decreases network-wide, and caching should actually become more effective, countering potential problems due to longer paths).

Hotfixes for 1481: Reduce peer count scaling to reduce CPU load during routing

---

README.md
src/freenet/client/filter/ContentFilter.java
src/freenet/client/filter/FilterCallback.java
src/freenet/client/filter/M3UFilter.java
src/freenet/clients/http/ExternalLinkToadlet.java
src/freenet/l10n/freenet.l10n.en.properties
test/freenet/client/filter/M3UFilterTest.java
test/freenet/client/filter/m3u/safe.m3u
test/freenet/client/filter/m3u/safe_madesafe.m3u
test/freenet/client/filter/m3u/unsafe.m3u
test/freenet/client/filter/m3u/unsafe_madesafe.m3u

This now makes all links absolute so the M3U list plays in more external players.
See the tests for details.
Once you run this code, the following should play the files in the tests:
cvlc http://127.0.0.1:8888/SSK@EjDPYvqYf9TKeo1w8k6YnrZRpwvYpUCNUo1jP40pV4g,m6AGnwlGbR8ZkNK6xEYsriGi-UUl4NjJKnIqSIF5iPQ,AQACAAE/stream.m3u
To see copyright notes for the played songs, open the unfiltered file:
http://127.0.0.1:8888/SSK@EjDPYvqYf9TKeo1w8k6YnrZRpwvYpUCNUo1jP40pV4g,m6AGnwlGbR8ZkNK6xEYsriGi-UUl4NjJKnIqSIF5iPQ,AQACAAE/stream.m3u?forcedownload=true

add m3u filter again

---

src/freenet/clients/http/geoip/IPConverter.java
src/freenet/clients/http/staticfiles/baseelements.css

The IP address is really, _really_ close to the flag on the connection pages. I can’t be having with this.

Add small padding for flags

---

src/freenet/store/saltedhash/SaltedHashFreenetStore.java

In some very specific circumstances you can have the DB grow while the metadata shrinks... according to bug7102 it happens in the real world... so this fixes it.

fix bug7102: don't attempt to pre-allocate when we truncate

---

NEWS.md
src/freenet/clients/http/staticfiles/themes/winterfacey/theme.css

What was changed:
1. Logo doesn't get out from menu block
2. In dropdown menu options take 1 line, not 2 lines. So dropdown menu extends to the length of an option
3. Blocks became of the same size within 1 line
4. Blocks are centered (before they were left-side)
5. Buttons are displayed on the right next to the fields

improvement in Winterfacey

---

.travis.yml

Oracle JDK tests have been failing for some time. This pull request removes them and adds openjdk 9-13.

Travis without oracle but with more openjdk tests

---

src/freenet/support/io/PooledFileRandomAccessBuffer.java

Hypothesis: deserialization of PooledFileRandomAccessBuffers could cause multiple deserialization of the fds variable, including its closables, so it could deserialize the buffers multiple times.
Fix: transient fds, and deserialization that sets the static FDTracker.
This was not measured.

move the deserialization guard from FDTracker into PooledFileRandomAccessBuffer

---

src/freenet/config/IntOption.java
src/freenet/support/Fields.java
test/freenet/config/IntOptionTest.java
test/freenet/support/FieldsDurationTest.java

I noticed a bug that I added. This is a fix, but not ideal. Therefore, I will be glad of any help.
Related points:
- Two toString
- config.IntOption#toDisplayString
- config.IntOption#toString
- Single toInt - config.IntOption#parseString
- ConfigToadlet#L329

Fix config option with dimension (duration)

---

src/freenet/clients/http/ConnectionsToadlet.java
src/freenet/clients/http/complexhtmlnodes/PeerTrustInputForAddPeerBoxNode.java
src/freenet/clients/http/complexhtmlnodes/PeerVisibilityInputForAddPeerBoxNode.java
src/freenet/node/useralerts/PeersOffersUserAlert.java

The incorrect l10n prefix was used to render the boxes, and it’s not necessary anyway, as trust and visibility only ever apply to darknet peers, anyway, so the prefix was removed entirely.

Fix peer options box

---

src/freenet/client/async/BaseClientGetter.java
src/freenet/client/async/BaseClientPutter.java
src/freenet/client/async/BaseManifestPutter.java
src/freenet/client/async/ClientGetter.java
src/freenet/client/async/ClientPutter.java
src/freenet/client/async/ClientRequester.java
src/freenet/client/async/ManifestPutter.java
src/freenet/client/async/SimpleHealingQueue.java
src/freenet/client/async/USKFetcherWrapper.java
src/freenet/client/async/USKRetriever.java

As the `ClientCallback`’s only used functionality is to return a `RequestClient`, the client can simply be handed in instead of the callback, removing the need for fake callbacks.

Hand in request client directly

---

src/freenet/node/updater/NodeUpdateManager.java

- hasMetaStrings and isUSK check were being performed over the previous value (due to code duplication)
- It may cause the node to not be able to restart properly
Should fix https://freenet.mantishub.io/view.php?id=7128 and https://freenet.mantishub.io/view.php?id=7038

Run sanity checks against given value

---

build.gradle

The source code is encoded in utf-8, which is currently not specified.
This causes several issues:
- The following tests fail (at least under windows)
- Base64Test.testDecodeStandard 
- Base64Test.testEncodeStandard  
- The compiler generates several parsing errors during the compilation:
- error: unmappable character (0x9D) for encoding windows-1252
-...
Defining the source code encoding fixes these issues.

Added definition that source code is encoded in UTF-8  to gradl build definition

---

src/freenet/pluginmanager/PluginInfoWrapper.java

This will fix a number of weird “can not load class/file”
exceptions on shutdown in plugins.

Set context class loader when terminating plugin

---

src/freenet/node/PeerNode.java

The only part of the 'performance' patches given any sort of go-ahead. forgotten about years ago.

Reduce max backoff times.

---

src/freenet/node/LocationManager.java

Missing this might be causing stray defensive location changes right now.

Pitch black defense only if swapping enabled

---

src/freenet/node/LocationManager.java
src/freenet/node/simulator/RealNodePitchBlackMitigationTest.java
src/freenet/node/simulator/readme.txt

Preliminary Evaluation:
*Without mitigation, the pitch black attack is devastating:*
*The pitch black mitigation reduces location loss — and therefore data loss — during an ongoing attack:*
*After a devastating pitch black attack, the mitigation recovers a reasonable network-structure (the cycles here are more than factor 10 slower than for the other cases):*

Pitch black mitigation test

---

src/freenet/store/caching/CachingFreenetStore.java
test/freenet/store/RAMSaltMigrationTest.java
test/freenet/store/caching/CachingFreenetStoreTest.java
test/freenet/store/saltedhash/SaltedHashSlotFilterTest.java

Several store tests fail when run (on windows system).
**Update:**
Now each test is executed in its own directory, so tests should be able to be executed in parallel without conflicting.
There were several problems.
**Stores are not closed properly in tests** 
One problem was that in many places the stores were not closed correctly at the end of each test case, which kept their file handlers open.
On windows machines you cannot move or delete a file which has an open file handle pointing to it.
The file pointers in the stores were often only closed after they were garbage collected. Since the garbage collection run is unpredictable, the success of the test was unpredictable.
You could see this in the messages that the system complained that it could not move or delete certain files …

Fixed unreliable store store test cases

---

src/freenet/node/OpennetManager.java

slow peers have insufficient total bandwidth to support the inbound
bandwidth expectation of a fast peer due to square-root peer count
scaling.

fix peer scaling for very fast peers:

---

src/freenet/clients/http/ConnectionsToadlet.java

This is now possible (since 2013 where encoding by key==<base64> was added)

try replacing spaces by newlines in noderefs when parsing fails.

---

src/freenet/node/NodeStats.java

We have far more peers than 10 years ago to support the larger spread
in node bandwidth around the world.
This is accompanied by a change in wininstaller_innosetup and
java_installer to add -Xss256k to wrapper.conf which decreases the
minimum memory consumption per thread (for its stack) by 75%.

Increase default max threads to 1000

---

src/freenet/keys/FreenetURI.java
test/freenet/keys/FreenetURITest.java

I noticed that the suggested edition was not preserved when calling intern() in FreenetURI. Here is a unit test to prove this. This test currently fails.
I assume a fix would be simple enough, I haven't provided any. The consequences of a fix in fred and in the modules, I guess could be confusing so maybe fixing this method is not the best option.

Fix FreenetURI intern() to not forget edition of USK

---

src/freenet/io/comm/UdpSocketHandler.java

This commit will make this program more "future-proof" by preparing it for the latest major release of JNA, which is a dependency of this program.  There are some minor API-incompatible changes between JNA 4.5.2 (which this program uses as of now) and 5.x, and removal of `Pointer.SIZE` is one of them.  The replacement API is `Native.POINTER_SIZE`; see the first bug linked in the commit message for details.
This commit does not break compatibility with JNA 4.5.2 because `Native.POINTER_SIZE` is available in both 4.5.2 and 5.x, so you guys are still free to either stick with JNA 4.5.2 or update.  On some GNU/Linux distributions, like Gentoo, we might build this program against a newer JNA version (5.10.0), and we currently rely on a patch containing this commit to fix the incompatibility …

Replace Pointer.SIZE with Native.POINTER_SIZE for JNA 5.x

---

src/freenet/client/async/SplitFileInserterSegmentStorage.java

CRC32 can legally be 0000, so this had the chance to fail falsely.
It was implemented 2014 in one go for storage for splitfile inserts,
so I expect this to have been just a bug.

fix: this threw an exception if the checksum was exactly [0,0,0,0].

---

src/freenet/node/Node.java

*code sent on FMS, not written by me, reviewed by me*
The logic was wrong, causing all blocks written to the store to also
be written to the cache. The store is written to in about half the
speed of the cache. This means effective cache storage capacity is
only 50% of what it should be, the other 50% hold copies of the store.
Whenever we get an incoming request, we already check both the cache
and store to see if we can fulfill the request. We also already make
sure the block never gets promoted from store to cache later on.
This fix may improve total network capacity significantly.

Stop storing blocks twice

---

src/freenet/keys/FreenetURI.java

Support web+freenet: and ext+freenet: as protocol handlers since it doesn't look like freenet: is getting whitelisted any time soon.
https seems to work without the change, perhaps the host part is currently always being stripped before calling the function?  Added the check to allow it in case that ever changes.

Fix prefix detection to support https, web+freenet: and ext+freenet:

---

src/freenet/client/filter/CSSTokenizerFilter.java
src/freenet/client/filter/HTMLFilter.java
test/freenet/client/filter/CSSParserTest.java

FMS-message:
Word breaking is not fully supported right now.
What I'd need for Freenet-Quickstart is <wbr> as a html tag and "transition-duration" & "transition-delay" as css tags.
<wbr> indicates possible places for the browser to do a word break, which is very much needed for long USK that usually break the page layout because the browser does not break them at all.
This is a very easy fix, you can just add it to freenet.client.filter.HTMLFilter.getAllowedTagVerifiers().group2
----------
I need the css to show a popup with a help tooltip when hovering over a link. The popup should be visible for a second after the cursor leaves the link, so you can actually move your mouse to the popup and copy text from there. Right now the popup vanishes instantly - see the purple links I have on …

Add css transition and word-breaking support by naejadu

---

src/freenet/node/PeerNode.java

*Changes that look like they should be included even if we do not merge PR #746 , but they need more review.*

Announcement fixes cherry picked from pr 746

---

NEWS.md
src/freenet/l10n/BaseL10n.java
src/freenet/node/updater/MainJarUpdater.java

It used the FALLBACK_LANG to get the fallback lang, but
iterator().next() skipped to the next value, which is the raw key.
This had also broken our whole translation system.

Fix translations and UpdatedVersionAvailableUserAlert.updateNowButton

---

src/freenet/client/filter/HTMLFilter.java

This avoids injecting javascript (though secured with a strict CSP header) where it is not needed. The csp-header still ensures that no malicious javascript can leak from previous content of the page.
this was quite long in the making, but I hope that it finally makes the m3u support as clean as it should be. It is a bit less robust than before — if you omit the closing </body> tag, the m3u-player won’t be injected, but then: If you omit the </body>, you should get errors … — and the player is now at the end of the body, not in the head.
Moving to the end of the body may actually be a good thing; with the inline script, it should be ensured that it still registers the on DOM content loaded event before parsing is done.

only include the inline m3u player if the page contains media-tags

---

src/freenet/clients/http/ToadletContextImpl.java
src/freenet/clients/http/staticfiles/js/m3u-player.js

This increases the resilience against failing fragments (which do happen in Freenet, especially in live-streaming where the problem might actually be a failed upload).
The goal of this change is to enable listening in the background without having to interact with the freenet player after the initial start of playback.

m3u-player: skip tracks that fail.

---

src/freenet/clients/http/SimpleToadletServer.java

with JS enabled, a new install redirected from /wizard to /wiz with Javascript and then redirected back to /wizard due to the check for the first time wizard.

fix: first time wizard caused a startup loop with JS enabled (release blocker)

---

src/freenet/clients/http/FirstTimeWizardNewToadlet.java
src/freenet/clients/http/SimpleToadletServer.java

with JS enabled, a new install redirected from /wizard to /wiz with Javascript and then redirected back to /wizard due to the check for the first time wizard.
And filling out the first time wizard did not set the wizard filled out flag, so new users with Javascript enabled wouldn’t be able to get out of the wizard whatever they did.

fix: first time wizard caused a startup loop with JS enabled

---

src/freenet/client/HighLevelSimpleClientImpl.java
src/freenet/client/async/SingleKeyListener.java
src/freenet/node/LowLevelGetException.java

- fix negative maxsize per new fetch override
- also override maxTempLength
- LowLevelGetException also return the throwable because the error doesnt help, the real gets hidden
see: https://github.com/freenet/plugin-KeepAlive/pull/2

Fix KeepAlive error on new keys

---

src/freenet/node/RequestSender.java

For consideration. This would improve security (e.g. no possibility of attacker data source getting directly connected to request originator just by path folding), but it may have negative performance impacts, especially on new nodes who mostly get their peers from doing local requests.

No path folding at high HTL

---

src/freenet/config/SubConfig.java
test/freenet/config/PersistentConfigTest.java
test/freenet/config/SubConfigTest.java

The whole reason for this is that Fred logs messages at ERROR if a config file contains an option it does not know about. As the plan is to remove a number of options, not having these values show up in log files is a definite plus.

✨ Allow Registering of Ignored Options

---

src/freenet/clients/http/FileInsertWizardToadlet.java

In order:
- if seclevel maximum: always SSK
- last selection (CHK or SSK), if available
- otherwise SSK
(this was broken which was horrible UX: we know that usually SSK is better, so we should not force users to choose — enable them to choose, but do not force them)

Provide default Key Type for File Insert

---

build.gradle
src/freenet/support/SimpleFieldSet.java
test/freenet/support/SimpleFieldSetTest.java

This fixes https://freenet.mantishub.io/view.php?id=7197.
(I also sneakily updated the Hamcrest dependency to 2.2 because it has a couple more cool matchers and it doesn't need the -core/-library split anymore.)

Fix NPE When a SimpleFieldSet’s “subsets” Are Uninitialized

---

src/freenet/clients/http/ConnectionsToadlet.java
src/freenet/l10n/freenet.l10n.en.properties

This shows what the noderef will expose and can be an important warning to advanced users who have VPN addresses and real node addresses that they don’t want to show.
(in this case they’ll have to change the bindTo to the one address to use in the config)

Show the unencoded IP addresses before the noderef

---

src/freenet/clients/http/ConnectionsToadlet.java
src/freenet/clients/http/DarknetAddRefToadlet.java

Previously the noderef was hidden in basic mode to get people to send it as file, because line terminators made problems (\n vs \r\n vs \r) and inserted linebreaks broke the noderef.
It has been made much more resilient since then, so the added click is now a bigger problem than potential breakage due to corruption.

Show the noderef in basic-mode: it is now robust enough

---

src/freenet/support/JarClassLoader.java
test/freenet/support/JarClassLoaderTest.java

ServiceLoader uses the `ClassLoader.findResources()` method to locate its service definition files. The default implementation of `findResources()` returns an empty `Enumeration`, making it impossible to use ServiceLoader from plugins.

🐛 Fix JarClassLoader’s ability to work with ServiceLoader

---

build.gradle

Update junit to version 4.13.2
----
Newer version of junit has some enhancements.
https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.md
One of the needed things is the assertThrows() method,
which helps to improve try-catch blocks from the test code.
https://junit.org/junit4/javadoc/latest/org/junit/Assert.html#assertThrows(java.lang.Class,%20org.junit.function.ThrowingRunnable)
Some improvements are required in the tests code.
This update is a minor preparation for this work.

Update junit to version 4.13.2

---

build.gradle
test/freenet/client/CodeTest.java
test/freenet/client/DefaultMIMETypesTest.java
test/freenet/client/FailureCodeTrackerTest.java
test/freenet/client/FetchContextTest.java
test/freenet/client/OnionFECCodecTest.java
test/freenet/client/async/ClientRequestSelectorTest.java
test/freenet/client/async/PersistentJobRunnerImplTest.java
test/freenet/client/async/SplitFileFetcherStorageTest.java
test/freenet/client/async/SplitFileInserterStorageTest.java
test/freenet/client/filter/BMPFilterTest.java
test/freenet/client/filter/CSSParserTest.java
test/freenet/client/filter/ContentFilterTest.java
test/freenet/client/filter/FilterUtilsTest.java
test/freenet/client/filter/GIFFilterTest.java
test/freenet/client/filter/JPEGFilterTest.java
test/freenet/client/filter/M3UFilterTest.java
test/freenet/client/filter/MP3FilterTest.java
test/freenet/client/filter/OggBitStreamFilterTest.java
test/freenet/client/filter/OggFilterTest.java
test/freenet/client/filter/OggPageTest.java
test/freenet/client/filter/PNGFilterTest.java
test/freenet/client/filter/ResourceFileUtil.java
test/freenet/client/filter/TagVerifierTest.java
test/freenet/client/filter/TheoraBitstreamFilterTest.java

Improve tests in the `freenet.client` package
----
Depends on #822  and #824 
----
Adds improvements to the tests in the  `freenet.client` package:
* wraps input/output streams with try-with-resources
* removes duplication
* uses better assertion methods
* creates helper utility ResourceFileUtil
* adds better code formatting

Improve tests in the `freenet.client` package

---

src/freenet/node/NodeStats.java

If this was active, connecting was impossible, and NLM has been inoperable and unused for years.
Currently not removing the routing code, because that’s more risky and there are parts that might be useful to salvage (like tempered preference for nodes with better ping times).

Set the new load management option to ignored.

---

src/freenet/pluginmanager/OfficialPlugins.java

Before moving it back to the default list of plugins, we need to figure out a good user experience for it. At the moment either it does not work or it floods users with bad results.

Move Library to advanced plugins because new users tend to get lost

---

src/freenet/pluginmanager/OfficialPlugins.java

There were several reports from users that UPnP did not start. We should give UPnP2 more testing so we can enable it by default.

Move UPnP2 to normal plugins. It does not seem broken, but UPnP does

---

src/freenet/support/CurrentTimeUTC.java

Now `CurrentTimeUTC` uses newer `java.time` API.
This change also removes unnecessary synchronization on the `GregorianCalendar` object.

Replace GregorianCalendar with java.time.OffsetDateTime in CurrentTimeUTC

---

src/freenet/client/async/ClientRequester.java
src/freenet/client/events/SplitfileProgressEvent.java
src/freenet/clients/fcp/ClientGet.java
src/freenet/clients/fcp/ClientPut.java
src/freenet/clients/fcp/ClientPutDir.java
src/freenet/clients/fcp/RequestStatus.java
src/freenet/clients/http/Cookie.java
src/freenet/clients/http/SessionManager.java
src/freenet/support/CurrentTimeUTC.java
src/freenet/support/LRUCache.java
test/freenet/clients/http/CookieTest.java

Follow-up on discussion in #866

Deprecate CurrentTimeUTC

---

src/freenet/node/NodeCryptoConfig.java

As stated in the description of this option, if a large portion of the network disables packet padding it makes the network easier to trace. 15 years later now, if network overhead is a real concern for some users they can tweak this themselves.

 Remove security lowering kludge.

---

src/freenet/node/Node.java

There were no restraints on negative values or extremely large values of amountOfDataToCheckCompressionRatio. Add a less than zero and a max of 100 MiB check.

Apply sanity check for size

---

src/freenet/client/filter/CSSTokenizerFilter.java
src/freenet/client/filter/ElementInfo.java
test/freenet/client/filter/CSSParserTest.java

- Support CSS combinators, i.e. a ~ b
- support more attribute selectors
- support :checked

Css improvements 2022: combinators, attribute-selectors, and :checked

---

src/freenet/io/comm/UdpSocketHandler.java

Throwing backtraces is needlessly expensive and spams the log with no additional gain.

Use logging instead of backtrace for IPv6-addresses when unsupported

---

src/freenet/crypt/Hash.java
test/freenet/crypt/HashTest.java

In the Guix build Hash.java was a blocker that had to be circumvented, because the i2p tools are not packaged.
Since the two methods providing NativeBigInteger are unused, this PR removes them completely.

Remove hash generation to native big integer to reduce dependencies.

---

src/freenet/support/SortedIntSet.java

This change is needed to compile on Java 21.

Java 21 fix: int used as return type but integer required

---

.github/workflows/package.yml

Actions updated due to [deprecation actions on Node v16](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
Fixed cache in "Setup Java" action
Changed installation via apt to another action with cache

[CI] Update actions, fix actions cache

---

test/freenet/support/JarClassLoaderTest.java

Java 11’s new, non-native `ZipFile` implementation will return the same entry if you ask for an entry with the same name twice, whereas Java 8’s native implementation gave you the _next_ entry with the given name, leading to a test that will work with Java 8 but not with Java 11.
And also, all the hubbub with multiple entries in a JAR file with the same name is totally unnecessary, the test works just fine, the fixed version doesn’t even need reflection, and it verifies `JarClassLoader`’s functionality just as well as before.
Tested with Java 8, Java 11, Java 17, and Java 21.

🐛 Fix JarClassLoaderTest to work with newer Java versions

---

src/freenet/node/FailureTable.java

Since we have 5 minutes time to receive a USK update, RF should be at most that long. Otherwise RF will block keys if the uploader checked them a bit too early.

Reduce recently failed and data not found wait times

---

src/freenet/clients/http/StatisticsToadlet.java

This empty box looks like something's wrong. Hide it when new load management is disabled.

Hide new load management statistics

---

src/freenet/clients/http/ConnectionsToadlet.java
src/freenet/io/AddressIdentifier.java
src/freenet/io/Inet4AddressMatcher.java
src/freenet/io/Inet6AddressMatcher.java
src/freenet/node/PeerNodeStatus.java
test/freenet/io/AddressIdentifierTest.java
test/freenet/io/Inet6AddressMatcherTest.java

Compacted IPV6 address like `::1` and `2001:db8::1234` can now be used. Connections page show IPV6 address like `[address]:port`.

Support abridged IPv6 address

---

build.gradle

When using the gradle-daemon to build a project, the working directory the script is executed in is the local directory of the gradle-daemon running the script. By explicitely specifying the directory to execute Git in, this will now work with and without gradle-daemon.

🐛 Run Git from the project directory

---

build.gradle

The default `jar` task a pre-defined input with `compileJava`’s output, which includes the original, non-replaced `Version.class`. I have not found a way to disable the pre-defined input, or modify it in a way that would still allow me to add a `Version.class` from a different task’s output.
What’s happening now is that there is a new task, `buildJar`. It is an almost verbatim copy of what the `jar` task previously contained with an added input (`compileVersion`’s output). This `Jar` task does not have a pre-defined input and as such only includes what is being specified.
The original `jar` task has been disabled and has been given the `buildJar` task as dependency. That way the `jar` task can still be run from the command line where it doesn’t do anything (because it’s disabled) but it …

Build JAR File Correctly

---

devnotes/licenses/cryptics-general-license.txt

source: https://web.archive.org/web/20030810151504/http://www.cryptix.org/docs/license.html

Add copy of the cryptics general license (2-clause BSD)

---

src/freenet/client/Metadata.java
src/freenet/client/async/KeyListenerTracker.java
src/freenet/client/async/SplitFileFetcherKeyListener.java
src/freenet/clients/fcp/ClientPut.java
src/freenet/crypt/HashType.java
src/freenet/crypt/SHA256.java
src/freenet/keys/CHKBlock.java
src/freenet/keys/ClientCHKBlock.java
src/freenet/keys/ClientKSK.java
src/freenet/keys/ClientSSK.java
src/freenet/keys/InsertableClientSSK.java
src/freenet/keys/Key.java
src/freenet/keys/NodeSSK.java
src/freenet/keys/SSKBlock.java
src/freenet/node/FNPPacketMangler.java
src/freenet/node/LocationManager.java
src/freenet/node/MasterKeys.java
src/freenet/node/updater/MainJarDependenciesChecker.java
src/freenet/pluginmanager/PluginManager.java
src/freenet/store/saltedhash/CipherManager.java
src/freenet/support/io/BucketTools.java
test/freenet/crypt/HMAC_legacy.java

During review of #831 it was observed that the overhead of pooling outweights that of constructing new digest instances.
This PR removes the pooling mechanism from the SHA256 helper class. Because the return-to-pool method is now a no-op, its usages are removed. The method is now deprecated, but remains for backwards compatibility.
While cleaning up I encountered the HashType enum, which had a special case for pooling of SHA-256 too. This deprecates the related return-to-pool method, and removes the special handling of SHA-256 message digest creation in this class.

Remove pooling and other special cases for SHA-256 digests

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

Update CSS filter

---

src/freenet/node/PeerNode.java

From what I can understand from the logic, this would cause transfer backoff to not be taken into account for bulk.
* The realtime parameter of getRoutingBackedOffUntil was set to `true` for both realtime and bulk.
* The bulk backoff parameter in getPeerNodeStatus was not used due to it having the wrong name (the equally named field was used instead).
Fixes db3329d567679c562f280aad53b80713aa19d73a

Fix copy-paste errors in backoff

---

src/freenet/clients/http/BookmarkEditorToadlet.java
src/freenet/clients/http/staticfiles/themes/winterfacey/theme.css

Fixes https://freenet.mantishub.io/view.php?id=6142 and https://freenet.mantishub.io/view.php?id=6087.
Additionally visually improves the bookmark management page under the Winterfacey theme that was hardly usable due to lack of indentation.
Before:
After:

Fix NPE and related issues in bookmark management

---

src/freenet/keys/ClientCHK.java
src/freenet/keys/ClientSSK.java
src/freenet/keys/FreenetURI.java
src/freenet/support/ByteArrayWrapper.java

Unsafe patterns regarding caching and reuse of mutable values are used throughout fred's code.
This fixes some of the most obvious ones by preventing byte[] instances from being shared.

Improve safety around byte[] handling

---

.github/workflows/package.yml

Wrapper validation now hosted at gradle/actions repo.

CI: update Gradle wrapper validation to latest version

---

src/freenet/io/comm/UdpSocketHandler.java

While reflection on Java's internals is slowly being crippled, Unsafe access is still possible (at least until JEP 417 [0] reaches phase 3 in Java 26 or later).
This requires moving from DatagramSocket to DatagramChannel as the former is substantially rewritten in Java 15 (JEP 373, see [1]) as a wrapper around the latter. The channel-based socket cannot be used in Java versions prior to 14 due to Java bug JDK-8232673 [2] which prevents read/write concurrency, effectively stalling the node.
Tested on OpenJDK 8, 11, 17, 21, 23, and 24.
Fixes bug 07217.
[0] https://openjdk.org/jeps/471
[1] https://openjdk.org/jeps/373
[2] https://bugs.openjdk.org/browse/JDK-8232673

Support IPV6_ADDR_PREFERENCES until Java 24 and beyond

---

src/freenet/support/Logger.java

No sane logger method has System.exit() as a side effect. Fortunately this log method is never used anywhere in Fred. Let's assume it is not used in plugins either and remove it.

Remove dangerous Logger.fatal(...) method

---

src/freenet/node/DNSRequester.java
src/freenet/node/PeerNode.java

Only sort the list nominalPeer when necessary.
That sorting can cause Pings to be sent. Now sorting is only done when
receiving a new noderef and at random intervals.
This should make the node less visible in DNS requests and Pings (more
typical pattern instead of requesting all peers at the same time).
Also it fixes the startup time regression by not doing a ping in the
PeerNode constructor.
The sorting result in the constructor was overwritten anyway …

Reduce pings and dns lookups

---

src/freenet/io/comm/DMT.java
src/freenet/io/comm/Message.java
src/freenet/node/BasePeerNode.java
src/freenet/node/MessageItem.java
src/freenet/node/NewPacketFormat.java
src/freenet/node/NodeDispatcher.java
src/freenet/node/NodeStats.java
src/freenet/node/PeerMessageQueue.java
src/freenet/node/PeerNode.java
test/freenet/node/MessageWrapperTest.java
test/freenet/node/NewPacketFormatTest.java
test/freenet/node/NullBasePeerNode.java
test/freenet/node/PeerMessageQueueTest.java

This code was effectively inactive since 2013 (which is when the FIXME in PeerNode.makeLoadStats was added: "re-enable when try NLM again").
Removing the related code not only gets rid of a few hundred lines of code, but also slightly reduces the (huge) number of things PeerNode needs to keep track of and simplifies the NPF logic substantially.
Note: this does not remove receiving of load stats from peer nodes.

Remove code related to NLM load sending

---

src/freenet/io/comm/IOStatisticCollector.java
src/freenet/io/comm/UdpSocketHandler.java

This removes a bunch of complicated but unused code, and makes the stats collector interface more self-explanatory.

Simplify IO statistics collection for UdpSocketHandler

---

src/freenet/support/io/FileUtil.java

There are a lot of `while (not completed reading/writing) { read/write some more! }` implementations in FileUtil for similar purposes. Reuse existing `copy` and `readUTF` implementations where possible.

Reduce stream handling duplication in FileUtil

---

src/freenet/clients/fcp/FCPConnectionInputHandler.java
src/freenet/clients/fcp/FCPConnectionOutputHandler.java
src/freenet/clients/fcp/FCPServer.java
src/freenet/clients/http/SimpleToadletServer.java
src/freenet/io/NetworkInterface.java
src/freenet/node/CHKInsertHandler.java
src/freenet/node/CHKInsertSender.java
src/freenet/node/DNSRequester.java
src/freenet/node/IPDetectorPluginManager.java
src/freenet/node/LocationManager.java
src/freenet/node/LoggingConfigHandler.java
src/freenet/node/Node.java
src/freenet/node/PacketSender.java
src/freenet/node/Persister.java
src/freenet/node/RequestHandler.java
src/freenet/node/RequestSender.java
src/freenet/node/RequestStarter.java
src/freenet/node/SSKInsertHandler.java
src/freenet/node/SSKInsertSender.java
src/freenet/node/TextModeClientInterface.java
src/freenet/node/TextModeClientInterfaceServer.java
src/freenet/support/Logger.java
src/freenet/support/PrioritizedTicker.java
src/freenet/support/compress/RealCompressor.java
src/freenet/support/transport/ip/IPAddressDetector.java

The PID logging is always disabled and there is no API for enabling it. Remove the entire class and all the calls to its logPID method.

Remove Logger.OSThread-based PID logging that was always disabled

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

Supported the following new CSS properties:
1. margin-block
2. margin-block-end
3. margin-block-start
4. margin-inline
5. margin-inline-end
6. margin-inline-start
7. padding-block
8. padding-block-end
9. padding-block-start
10. padding-inline
11. padding-inline-end
12. padding-inline-start
13. scroll-behavior
14. scroll-snap-align
15. scroll-snap-stop
16. scroll-snap-type

Add margin-*, padding-*, scroll-snap-* CSS properties

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

Fix incorrect CSS property names for `border-top-left-radius`, `border-top-right-radius`, `border-bottom-left-radius`, `border-bottom-right-radius`

Update CSS properties

---

src/freenet/node/DNSRequester.java

This needs to be merged and released as emergency release, because it turns darknet nodes with 100% connected nodes into electrical heaters.

fix busy loop if all darknet peers are connected.

---

src/freenet/node/FailureTable.java

Creating backtraces isn’t free and a user reported that they see a lot of these errors in the log. But the behavior is expected if you’re connected to a node with build 1497 or earlier.

Fix: only log errors when the time was invalid in 1497, too

---

src/freenet/node/PeerMessageQueue.java

over 5 hops that gives a 10% chance to delay a realtime packet. With 10% that was at 40%, severely impacting the time critical realtime routing.

reduce 10% chance for bulk to 2%

---

src/freenet/node/PeerNode.java

Maximum ping times between Frankfurt consistently stay below 50ms, so since most friend nodes will be in the same country, a minimum RTO of 1 second likely inflated latency unnecessarily.
Lots of old constants …

Reduce minimum retransmission timeout (RTO)

---

src/freenet/support/TimeUtil.java
test/freenet/support/TimeUtilTest.java

The time intervals were subtly broken:
* Parsing 0.1s would yield 1 ms instead of the correct 100 ms. Fix this by parsing the seconds.millis as fractional seconds.
* Formatting would format fractional seconds locale-sensitively where parsing would assume point as a decimal separator, so toMillis(fromMillis(...)) would fail depending on locale. Fix this by always formatting in the root locale (decimal point).
As a tiny bonus, time interval parsing is now approximately 3x faster.

Refactor TimeUtil: use Java 8 Date-Time API and improve time intervals

---

src/freenet/node/PeerManager.java

The previous code nested too much error handling even though many parts are independent.
This is a cleanup as sideeffect of trying to multi-thread the peer initialization. That multi-threading turned out to be unnecessary, but the cleanup is nice without it.

refactor: split parsing peers into multiple steps

---

src/freenet/support/io/FileUtil.java
src/freenet/support/io/ZeroInputStream.java

By substituting the CipherInputStream that is used as a random number source by a simple MersenneTwister, we no longer need to synchronize on the FileUtil class for each 32k bytes written. The MersenneTwister itself is sufficiently cheap to create on the fly.

Don't synchronize on the class while writing in FileUtil.fill(...)

---

src/freenet/client/async/ClientGetter.java
src/freenet/client/async/ClientLayerPersister.java
src/freenet/clients/http/bookmark/BookmarkManager.java
src/freenet/config/FilePersistentConfig.java
src/freenet/io/AddressTracker.java
src/freenet/l10n/BaseL10n.java
src/freenet/node/Node.java
src/freenet/node/OpennetManager.java
src/freenet/node/PeerManager.java
src/freenet/node/Persister.java
src/freenet/node/updater/LegacyJarFetcher.java
src/freenet/node/updater/MainJarUpdater.java
src/freenet/node/updater/NodeUpdateManager.java
src/freenet/node/updater/UpdateOverMandatoryManager.java
src/freenet/pluginmanager/PluginManager.java
src/freenet/store/saltedhash/SaltedHashFreenetStore.java
src/freenet/support/FileLoggerHook.java
src/freenet/support/io/BaseFileBucket.java
src/freenet/support/io/FileUtil.java

Copy was implemented through InputStream/OutputStream. The OS will be perfectly capable of doing this, no need to read and write the individual bytes. Use NIO's `Files.copy` to perform the copy instead.
Rename and move had two separate implementations without a compelling difference (apart from `renameTo` being unable to move across filesystem boundaries). Unify the two implementations and use the NIO's `Files.move` to move the file atomically, or if that fails, non-atomically.

Use NIO helpers in FileUtils for copy/move/rename

---

src/freenet/client/async/USKDateHint.java
test/freenet/client/async/USKDateHintTest.java

This also fixes a bug with the week-based hints returning the same value for the start of the year and the end of the year.

Rewrite USKDateHint using Java 8 Date-Time APIs (fixing week hints)

---

src/freenet/node/NewPacketFormat.java

This synchronized on the sendBufferLock, blocking package sending during received message handling.
Big thanks to Yonghuan Xu for the catch!

Fix synchronization of receive buffer

---

src/freenet/support/JarClassLoader.java
test/freenet/support/JarClassLoaderTest.java

JAR (ZIP) files are technically not required to have directory entries; it is absolutely fine for a JAR file to only have a `META-INF/MANIFEST.MF` entry, without a corresponding `META-INF` directory entry.
If a JAR file does have separate entries for directories, though, the `getResource()` and `getResources()` methods are expected to return URLs for these entries. Our `JarClassLoader` did not do that.
The problem occured when I was working with Flyway and its classpath scanning: it refused to locate the directory in the classpath that the migration scripts were stored in. After much debugging it was found that the name of the directory is handed in to `getResources()` without a trailing slash, but the `JarClassLoader` uses the `ZipEntry.getName()` method to get the name of the current …

🐛 Allow Class Loader to Enumerate Directory Entries

---

src/freenet/crypt/AEADInputStream.java
src/freenet/crypt/AEADOutputStream.java
src/freenet/crypt/BlockCiphers.java
test/freenet/crypt/BlockCiphersTest.java

On modern Java, the JCE implementation is about twice as fast as BC.

Use JCE AES implementation for AEAD when available

---

src/freenet/crypt/AEADInputStream.java
src/freenet/crypt/EncryptedRandomAccessBucket.java
src/freenet/support/ByteBufferInputStream.java
src/freenet/support/io/PaddedBucket.java
src/freenet/support/io/PaddedRandomAccessBucket.java
src/freenet/support/io/RAFInputStream.java

There are multiple places where the read byte is not correctly converted to unsigned int (leading to incorrect data being returned), or where the single-byte `read()` path differs from the multi-byte `read(byte[])` or `read(byte[], int, int)` path.
Additionally, do not fear creating short-lived single-byte buffers - their overhead is minimal and can likely be optimized away to some extent.

Fix single-byte `read()` in various InputStream implementations

---

src/freenet/crypt/ChecksumChecker.java

This would enable using RAM temp buckets for sufficiently small inputs.

Use length hint for bucket creation in ChecksumChecker

---

test/freenet/crypt/RandomShortReadInputStream.java

Returning 0 bytes in `InputStream` is only allowed when 0 bytes are requested (by setting the `length` parameter to 0). Otherwise, an `InputStream` is expected to block until at least one byte is available (yielding that byte) or until the end of the stream is reached (returning -1 as the return value).
This class is only used for testing, but still nice to have it conformant.

Return valid length from RandomShortReadInputStream.read

---

src/freenet/crypt/ciphers/Rijndael.java
src/freenet/crypt/ciphers/Rijndael_Algorithm.java

The synchronization appears to have been added at some point to limit overall crypto concurrency assuming a single-core processor, but in today's world, we'd rather get rid of such limits.

Do not synchronize on Rijndael cipher initialization or use

---

src/freenet/clients/http/ToadletContextImpl.java

There isn't broken HTTP clients. All headers are forced lower-case by HTTP/2. Don't need to do this a dozen times for every request.

Do not fix case of header key

---

src/freenet/crypt/Util.java

This method is used by Yarrow (our random number generator) for seeding, which is used in many places. We'd better not have a global bottleneck for its uses.
Instead of sharing a digest globally, just obtain a fresh one when in need.

Do not synchronize on global variable in crypt Util.makeKey

---

src/freenet/crypt/AEADCryptBucket.java

There is no need for synchronized here if we just make the field volatile. This change is unlikely to lead to actual performance gain in practical use cases, but at least it is a bit more concise.

Do not synchronize on access to AEADCryptBucket.readOnly

---

src/freenet/node/NodeStats.java

All the Hashtables can easily be replaced by ConcurrentHashMap. This reduces potential lock contention (see also #989 for related work) in the node stats reporting, and simplifies the code by using modern constructs like `computeIfAbsent` and factoring out common code.

Get rid of Hashtable in NodeStats

---

src/freenet/node/NodeStats.java

* Remove unused arguments for private methods
* Remove all kinds of unused fields, methods & constructors
Reduces the code size of this rather large class by roughly 110 lines.

Remove unused code and parameters from NodeStats

---

src/freenet/clients/http/StatisticsToadlet.java
src/freenet/node/NodeStats.java

Turns out I broke this 9 years ago, so let's fix it :smile: 
For those who don't have a memory of these statistics panels, it's these two:
---
The `count` was never incremented, and consequently the Incoming Request Distribution and Outgoing Request Distribution panels would no longer show up on the statistics page.
Instead of keeping track of the total count independent of the bins, just sum the bins when we need a total count for display purposes.
While we're at it, let's get rid of the synchronization too.

Fix request distribution stats

---

build.gradle
src/freenet/client/filter/GenericReadFilterCallback.java
src/freenet/clients/http/utils/L10nExtension.java
src/freenet/clients/http/utils/PebbleUtils.java
test/freenet/client/filter/ContentFilterTest.java
test/freenet/clients/http/utils/L10nExtensionTest.java
test/freenet/clients/http/utils/PebbleUtilsTest.java
test/freenet/l10n/BaseL10nTest.java
test/freenet/l10n/freenet.l10n.de.properties
test/freenet/l10n/freenet.l10n.de.test.properties
test/freenet/l10n/freenet.l10n.en.test.properties
test/freenet/support/TestProperty.java

Story Time!
I felt like working on a couple of tests, so I began with running all tests in IDEA, and behold, there were a bunch of tests that did not run. I started with `BaseL10nTest` and noticed that it ran on the command line with `./gradlew` (as it should!) but would only fail in the IDE. Some debugging later I found out that the IDE ran the tests from the project directory, but Gradle actually ran them from… 👀 within the classpath?! And there was a `TestProperty` class being used to provide relative paths for translation override files, but those were also overridden by Gradle? Apparently the reason for the overrides in Gradle is that what the methods in `TestProperty` did was so broken that changing `build.gradle` (and complicating the build) was the easier option; a large part of …

Fix Translation Handling in Tests

---

src/freenet/client/filter/HTMLFilter.java
test/freenet/client/filter/TagVerifierTest.java

Freesites should be able to set the robots tag to tell spiders on freenet to stop publishing them. Invalid robots value is filtered.
Freesites can also set referrer, and no-referrer is the only value supported.

Allow freesite to set robots, googlebot and referrer=no-referrer meta tag

---

src/freenet/client/filter/HTMLFilter.java
test/freenet/client/filter/ContentFilterTest.java
test/freenet/client/filter/TagVerifierTest.java

New elements [`<meter>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/meter), [`<progress>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/progress), `<input type="email">`, `<input type="number">`, `<input type="search">`, `<input type="tel">`, `<input type="url">`
Some of the input elements on Freenet may better use `<input type="search">` or `<input type="number">` than `<input type="text">`, so we should first support them.

Add HTML elements meter,progress,input type=email,number,search,tel,url

---

src/freenet/client/ArchiveManager.java
src/freenet/client/async/ClientContext.java
src/freenet/client/async/ClientRequestScheduler.java
src/freenet/client/async/ClientRequestSelector.java
src/freenet/client/async/InsertCompressor.java
src/freenet/client/async/SingleBlockInserter.java
src/freenet/client/async/USKManager.java
src/freenet/client/async/USKRetriever.java
src/freenet/node/useralerts/UserAlertManager.java
test/freenet/node/useralerts/UserAlertManagerTest.java

As the XML is currently being hand-built using a `StringBuilder`, it should come as no surprise that it breaks as soon as a user alert contains e.g. a `<` character.
This branch builds upon #1079.

Build the Atom XML correctly

---

src/freenet/client/filter/HTMLFilter.java
test/freenet/client/filter/ContentFilterTest.java

This branch aims to add support for ARIA properties in HTML filter.

Support ARIA role property

---

src/freenet/client/filter/CSSTokenizerFilter.java
test/freenet/client/filter/CSSParserTest.java

Add CSS properties isolation,object-position,pointer-events,rotate,row-gap

Add CSS properties

---

src/freenet/crypt/OCBBlockCipher_v149.java

This saves about 10% time on AES block processing for AEAD buckets.
When combined with #1056 the improvement is even more substantial.

Optimize OCBBlockCipher_v149 by replacing Vector with List

---

src/freenet/clients/http/FProxyToadlet.java
src/freenet/clients/http/QueueToadlet.java

This leaked the username — thank you for the report!
Currently there are no known public gateway nodes running, so exposing the fix here is safe.
There may also be leaked IP values that still need to be fixed: patches welcome (to speed this up).

Do not show download to disk for large file page on public gateway

---

src/freenet/clients/http/PproxyToadlet.java
src/freenet/pluginmanager/OfficialPlugins.java

Make advanced:
- JSTUN contact external server ⇒ needs understanding of effects
- MDNSDiscovery announces in LAN ⇒ need understanding of effects
- ThawIndexBrowser: we have almost no Thaw indexes ⇒ hard to understand
- UPnP: should usually choose UPnP2 instead
Make simple:
- KeyUtils: may be technical, but is pretty easy to use

Official plugins visibility adjustment

---

src/freenet/clients/http/ToadletContextImpl.java

Added recommended headers by https://developer.mozilla.org/en-US/docs/Web/API/Window/crossOriginIsolated. This allows freenet tabs to be hosted in separate OS process to mitigate some risks.

Make fproxy cross origin isolated

---

src/freenet/client/filter/HTMLFilter.java

Fix rel attribute and add rel values noopener,nofollow,noreferrer,external,tag
Also fixed code style related to adding items to HashSet.

Fix rel attribute and add rel values

---

src/freenet/support/io/Fallocate.java

Sorry, there were some issues that GitHub does not let me to update the branch with changes to GitHub actions, so I recreated #1008. Original indentation style is restored. fd with the value 0 is never actually used. I'm not sure what is unsafe to write a byte at the end of a file on Windows. The data written is not going to be used other than to allocate disk space, and filling the file with random data instead of zeros can shorten SSD life time. I have run this code on Windows.

Fix unhandled UnsupportedOperationException in Fallocate

---

src/freenet/l10n/NodeL10n.java
test/freenet/l10n/BaseL10nTest.java
test/freenet/node/useralerts/UserAlertManagerTest.java

The test was using the wrong translation file, i.e. the production translation. By forcing it to use the translation file used in tests of the translation system, any key that does not exist in that file (which is pretty much every key outside of tests) will return the key as translation, making it trivial to test that the correct key is requested.

Fix UserAlertManager Test

---

src/freenet/io/xfer/BlockTransmitter.java

The timed wait(int) method behaves like an untimed wait() when its argument is zero, effectively stalling the thread until they are waken up for other reasons. Since the MAX_ARTIFICIAL_FINAL_PACKETS_DELAY is 1000 millis and a delay is used for the last two packets this will impact 0.2% of the jobs, causing a thread leak.
Use wait(int, long) to pass an additional nanosecond of waiting time to prevent the wait time from ever being zero.
Please review and test carefully. There is also #1087 that removes the blocking wait altogether, but that one is somewhat more complex.

BlockTransmitter: prevent 0.2% of jobs from stalling

---

src/freenet/client/filter/HTMLFilter.java
test/freenet/client/filter/TagVerifierTest.java

I'm so sorry this bug was introduced, and the tests are completely unable to catch it.

Fix NullPointerException in input tag filter

---

src/freenet/crypt/MultiHashDigester.java
src/freenet/crypt/MultiHashInputStream.java
src/freenet/crypt/MultiHashOutputStream.java
test/freenet/crypt/MultiHashDigesterTest.java
test/freenet/crypt/MultiHashInputStreamTest.java
test/freenet/crypt/MultiHashOutputStreamTest.java

Simplify MultiHashInputStream and MultiHashOutputStream by extracting their common multi-digest hashing code into a separate class.
Additionally, ensure that MultiHashInputStream does not advertise or implement mark/reset support (default delegated to the underlying InputStream by FilterInputStream), as this could lead to digesting the same bytes multiple times.

Simplify MultiHashInputStream and MultiHashOutputStream

---

src/freenet/io/xfer/BlockReceiver.java
src/freenet/io/xfer/BlockTransmitter.java
src/freenet/node/RequestSender.java
src/freenet/support/math/BootstrappingDecayingRunningAverage.java
src/freenet/support/math/DecayingKeyspaceAverage.java
src/freenet/support/math/MedianMeanRunningAverage.java
src/freenet/support/math/RunningAverage.java
src/freenet/support/math/SimpleRunningAverage.java
src/freenet/support/math/TimeDecayingRunningAverage.java
src/freenet/support/math/TrivialRunningAverage.java
test/freenet/support/math/BootstrappingDecayingRunningAverageTest.java
test/freenet/support/math/DecayingKeyspaceAverageTest.java
test/freenet/support/math/SimpleRunningAverageTest.java
test/freenet/support/math/TimeDecayingRunningAverageTest.java

the RunningAverage implementations have various issues:
* Too many responsibilities (like TimeDecayingRunningAverage, that tries to keep track of clock skew in the middle of its calculations)
* Too much mutable state (like SimpleRunningAverage, that keeps track of "how many items do I have" across 3 different fields)
* A generous amount of synchronization, but not everywhere
* Leftover methods from earlier times (custom serialization formats and unused code that does who-knows-what)
* A large amount of empty Javadoc comment
* A general lack of consistency in code formatting
* Zero tests
This PR attempts to improve the situation by:
* Separating out the clock skew tracking & reporting out of the main logic of TimeDecayingRunningAverage (and using a monotonic clock for the actual …

Cleanup RunningAverage implementations

---

build.gradle

I have a local branch that adds a task to add the source JAR file that I use for uploading to my Maven repository, and I wondered, “why do I keep this from you?” So here you have it. 😁

Add Task to Build Source JAR
