- src/freenet/pluginmanager/PluginManager.java
This fixes the review results of https://github.com/freenet/fred/pull/275 which was merged before they were resolved.
> PluginManager: JavaDoc tweaks

- src/freenet/clients/http/Toadlet.java
This fixes the review results of https://github.com/freenet/fred/pull/265 which was merged already, which is why the results have to be fixed in this fresh pull request.
> Toadlet.showAsToadlet(): Documentation tweaks

- src/freenet/client/async/ClientPutter.java
- src/freenet/client/async/SplitFileInserter.java
- src/freenet/client/async/SplitFileInserterStorage.java
- src/freenet/client/async/SplitFileInserterStorageCallback.java
Should fix bug #6457 and a related bogus error message.
> Fix GetCHKOnly

- test/freenet/client/async/SplitFileInserterStorageTest.java
- test/freenet/support/io/BarrierRandomAccessBuffer.java
> Fix bug 6459 flaky unit test

- src/freenet/clients/http/QueueToadlet.java
Fix bug where listFetchKeys.txt from uploads page gave download keys by
implementing listing of uploads and renaming the file to listKeys.txt
> Fix bug 6513 Implement text list of inserted keys.

- src/freenet/clients/fcp/ClientPutBase.java
> Fix bucket leak on non-persistent inserts.

- src/freenet/client/async/SimpleHealingQueue.java
- src/freenet/client/async/USKManager.java
- src/freenet/clients/fcp/ClientRequest.java
- src/freenet/clients/fcp/FCPConnectionHandler.java
- src/freenet/clients/http/FProxyToadlet.java
- src/freenet/node/Node.java
- src/freenet/node/RequestClient.java
- src/freenet/node/RequestClientBuilder.java
- src/freenet/node/simulator/LongTermManySingleBlocksTest.java
- src/freenet/node/updater/LegacyJarFetcher.java
- src/freenet/pluginmanager/PluginManager.java
Adds a `RequestClient` builder that is easy to use and cuts down on the number of anonymous classes created.
> RequestClient builder

- src/freenet/client/Metadata.java
- src/freenet/clients/fcp/FCPConnectionOutputHandler.java
- src/freenet/support/compress/RealCompressor.java
It might explain some of the "Stalling" several users have reported over the years.
> Misc fixes inspired from coverity reports

- src/freenet/node/NodeClientCore.java
- src/freenet/support/compress/RealCompressor.java
RealCompressor in 1468 is way too complicated for what it does... this simplifies it and makes the error handling more resilient.
Please test it before merging it.
> Simplify RealCompressor

- src/freenet/client/async/InsertCompressor.java
The compression algorithm choice is now dependant on number of blocks rather than compression ratio from byte size
> Bug6591: improve compression algorithm choice

- .classpath
> Upgrade the eclipse buildfile for Bouncycastle 1.52

- src/freenet/client/filter/HTMLFilter.java
This change allows freesites to set a favicon which is shown in the browser tab.
> Allow icons in <link> tags

- src/freenet/node/updater/UpdateOverMandatoryManager.java
This may make inserts work better for the first several hours after restarting... Please review carefully as with all updater code, and it will need to be tested too.
For 1469 or later!
> Updater insert main jar less often

- src/freenet/node/PeerNode.java
> Delete unused code.

- src/freenet/client/async/BaseManifestPutter.java
at least one plugin uses it: SchwachkopfEinsteck (gitplugin)
> set addItem to public

- README.building.md
- README.md
This basically fixes what I complained about in devl today.
> improve our READMEs with build instructions

- src/freenet/clients/http/StatisticsToadlet.java
> Show peer locations, not distance in peer location histogram

- src/freenet/l10n/BaseL10n.java
Thanks to vwoodzell for the report.
> BaseL10n: fix Bokmål slug

- src/freenet/node/LocationManager.java
- src/freenet/node/PeerManager.java
> Purge LocationUIDPair.

- src/freenet/clients/fcp/AddPeer.java
- src/freenet/clients/http/ConnectionsToadlet.java
- src/freenet/node/Announcer.java
- src/freenet/node/DarknetPeerNode.java
- src/freenet/node/FNPPacketMangler.java
- src/freenet/node/Node.java
- src/freenet/node/NodeCrypto.java
- src/freenet/node/OpennetManager.java
- src/freenet/node/OpennetPeerNode.java
- src/freenet/node/PeerManager.java
- src/freenet/node/PeerNode.java
- src/freenet/node/SeedClientPeerNode.java
- src/freenet/node/SeedServerPeerNode.java
This is preparing for next phase: 623a239 should be cherry-picked even if the rest isn't
Odds are we can't remove more of the DSA code until this has been deployed and is mandatory (without breaking opennet)
> Cleanup noderefs

- src/freenet/node/FNPPacketMangler.java
- src/freenet/node/NodeCrypto.java
- src/freenet/node/PeerNode.java
Mostly deleting obsolete code and updating comments.
> Minor FNP cleanups

- src/freenet/node/NodeCrypto.java
> critical bugfix following #440

- src/freenet/store/caching/CachingFreenetStoreTracker.java
- test/freenet/store/caching/CachingFreenetStoreTest.java
Refactoring and test improvements. Low priority but smallish.
> More caching store cleanup (low priority)

- src/freenet/node/NodeCrypto.java
Sorry, recent regression in 26893bca7f969c6e77a9cf0d1e6776d85f74d82b
> Fix NPE on creating a new node, argh!

- .travis.yml
> Configure travis to test with java8 instead of java6

- src/freenet/node/NewPacketFormat.java
- test/freenet/node/NewPacketFormatTest.java
- test/freenet/node/NullBasePeerNode.java
This fixes the indentation/formatting problems as well as resolve the problem without changing the HMAC API
> An alternative to #482 and #483

- NEWS.md
to reduce the load on the maintainers.
> update NEWS file

- src/freenet/client/async/DefaultManifestPutter.java
- src/freenet/clients/http/FProxyToadlet.java
- src/freenet/clients/http/wizardsteps/BANDWIDTH_MONTHLY.java
- src/freenet/node/Node.java
This is just small stuff, but should matter for usability.
> Update default config

- src/freenet/clients/http/ChatForumsToadlet.java
This ensures that people always get the newest version of the pages. I hope it prevents some failures when trying to run an outdated Sone.
> chat page: use negative usk numbers

- src/freenet/clients/http/PproxyToadlet.java
When reloading plugins loaded from disk, the cached version is not used, anyway.
> Hide “remove from cache” checkbox for plugins loaded from disk

- src/freenet/support/URLEncoder.java
- test/freenet/support/URLEncoderDecoderTest.java
This fixes [bug 6763][bug].
[bug]: https://bugs.freenetproject.org/view.php?id=6763
> Always URL-encode non-ASCII space characters

- src/freenet/l10n/freenet.l10n.en.properties
- src/freenet/pluginmanager/OfficialPlugins.java
Thanks to ArneBab for reviewing it and readying it for inclusion!
> Add Sharesite as an official plugin

- src/freenet/node/LocationManager.java
Should be trivial log fix for swapping. But needs testing on actual darknet nodes, or at least on a hybrid node (such as mine).
> Recreate message, as required

- src/freenet/node/NewPacketFormat.java
- src/freenet/node/PacketFormat.java
- src/freenet/node/PeerNode.java
Fixes keepalives in NewPacketFormat (regression with NewPacketFormat, years ago). This makes multi-node-one-VM simulations much faster and more reliable, but also should improve reliability of low traffic connections generally.
> Fix keepalive

- src/freenet/client/Metadata.java
- src/freenet/client/async/KeyListenerTracker.java
- src/freenet/client/async/SplitFileFetcherKeyListener.java
- src/freenet/client/async/SplitFileFetcherStorage.java
- src/freenet/support/BloomFilter.java
This adds additional sanity checks and makes the KeyListener code more resilient to malicious splitfiles.
> Hotfix for Frostbite

- src/freenet/l10n/BaseL10n.java
Fixes part of what was discussed at the original pull request https://github.com/freenet/fred/pull/500
For the remaining issues, I've filed https://bugs.freenetproject.org/view.php?id=6857
Will be used by the currently being developed WoT build0019.
> New language codes for WoT (was PR #500)

- src/freenet/node/Node.java
- src/freenet/node/NodeStats.java
- src/freenet/node/RequestStarter.java
- src/freenet/node/RequestStarterGroup.java
This removes a bunch of old load management complexity that is barely used in practice.
> Remove load limiting high level token buckets

- src/freenet/io/comm/MessageCore.java
- src/freenet/io/comm/MessageFilter.java
Some *low-hanging fruit* improvements on `MessageFilter`.
> Simple minor MessageFilter improvements

- src/freenet/support/PrioritizedTicker.java
- src/freenet/support/Ticker.java
- src/freenet/support/TrivialTicker.java
- test/freenet/support/CheatingTicker.java
- test/freenet/support/PrioritizedTickerTest.java
Clean up PrioritisedTicker a bit and add a test.
> Add test for remove()

- src/freenet/support/BloomFilter.java
Thanks to user oo on Frost for noticing, and user Ranger on FMS for
relaying the observation.
> Fix a corner case in BloomFilter length

- src/freenet/node/FNPPacketMangler.java
- src/freenet/node/NodeCrypto.java
This is the second part of #440 
DO NOT MERGE before 1471 is mandatory!
> Remove the DSA params from the noderefs

- src/freenet/node/NodeDispatcher.java
- src/freenet/node/NodeStats.java
This might fix the problem figaro is experiencing on IRC... and makes sense in any case
> Handle announcement loops

- src/freenet/crypt/ECDSA.java
Starting from BC 1.54 [0], ECDSA signatures are checked on whether they
occupy the entire byte array. If they do not, an exception is thrown.
This breaks the vast majority of JFK4 messages for users where BC
provides the ECDSA functionality. SunEC parses the padded signatures
just fine, as did BC 1.53.
As a workaround, parse the DER-encoded signature length and adjust the
signature length accordingly, effectively stripping the padding.
Thanks a lot, BouncyCastle developers, for introducing this far from
subtle, non-standard and completely unnecessary non-feature, and for
not mentioning it in your release notes.
[0] Introduced in d62b2f172e937dcbe8dd0a1ea614d24b2db88856, see
https://github.com/bcgit/bc-java/
> Force stripping ECDSA signature padding: BC 1.54 has retarded checks

- src/freenet/clients/http/SimpleToadletServer.java
- src/freenet/node/NewPacketFormat.java
- test/freenet/node/NewPacketFormatTest.java
The profiler has made these obvious...
> Improve upon a few low-hanging fruits

- src/freenet/node/NodeStarter.java
- src/freenet/support/ProcessPriority.java
This works for me on linux but needs wider testing.
> Implement the osx/linux glue for ProcessPriority

- src/freenet/crypt/SSL.java
- src/freenet/io/SSLNetworkInterface.java
This updates the SSL code so that it works on Java 8+ (as well as on Java 7), and uses more up-to-date crypto algorithms and protocols. In addition, this includes a few cleanups and error message improvements.
> Update SSL code

- src/freenet/store/saltedhash/SaltedHashFreenetStore.java
- src/freenet/support/io/Fallocate.java
Apparently error codes aren't the same cross-platform... ensure that we will always fail safe.
> Fix fallocate (again)

- NEWS.md
- src/freenet/clients/http/ToadletContextImpl.java
- src/freenet/clients/http/UserAlertsToadlet.java
- src/freenet/io/SSLNetworkInterface.java
- fix clickjacking vulnerability
- patch open redirect and header injection vulnerability introduced in 1476
- fix SSL which broke with Java7 due to missing cypher
Thanks to nextgens for the fixes!
This is what I plan to release as 1477.
> Stable 1477

- build.gradle
- src/freenet/clients/http/ToadletContextImpl.java
- src/freenet/io/SSLNetworkInterface.java
- test/freenet/crypt/MessageAuthCodeTest.java
- Update BC to 1.56
- Re-enable RSA-based ciphers
- Fix a potential click-jacking vulnerability with some browsers
> Misc SSL related fixes for next release

- README.building.md
- README.md
Convert plain links in README.md to markdown
Tidy README.building.md distro instructions
> Nice links in README's

- src/freenet/clients/http/PageMaker.java
- src/freenet/clients/http/staticfiles/themes/winterfacey/theme.css
this is from https://github.com/ArneBab/freenet-Winterfacey-theme
> add Winterfacey theme

- src/freenet/client/async/SplitFileFetcher.java
- src/freenet/support/io/BaseFileBucket.java
This should do the trick; I haven't tested it on windows
> bug6562: mark temporary files as hidden

- src/freenet/clients/http/BookmarkEditorToadlet.java
- src/freenet/clients/http/UserAlertsToadlet.java
- src/freenet/clients/http/WelcomeToadlet.java
- src/freenet/clients/http/bookmark/BookmarkItem.java
- src/freenet/clients/http/bookmark/BookmarkManager.java
- src/freenet/clients/http/staticfiles/bookmark.css
- src/freenet/node/useralerts/UserAlertManager.java
Based on https://github.com/freenet/fred/pull/588 to avoid merge conflicts.
Screenshot:
> Mark updated bookmarks with bold link; add button for dismissing updates

- src/freenet/support/io/BaseFileBucket.java
This fixes two of the tests that fail for me on @ArneBab’s `next` branch.
> Fix setting attributes on non-DOS systems

- src/freenet/node/updater/UpdateDeployContext.java
This allows running multiple nodes on the same machine.
> Fix regression: add relative jna tmpdir path to wrapper if not existing

- src/freenet/client/ArchiveManager.java
- src/freenet/support/io/SkipShieldingInputStream.java
for https://freenet.mantishub.io/view.php?id=6921
> commit COMPRESS-449 workaround

- src/freenet/crypt/KeyGenUtils.java
- test/freenet/crypt/KeyGenUtilsTest.java
this should fix https://freenet.mantishub.io/view.php?id=7023
> always use BouncyCastle in KeyGenUtils

- src/freenet/clients/http/staticfiles/themes/winterfacey/theme.css
The theme becomes much cleaner.
> winterfacey theme adaptions by poets

- src/freenet/clients/http/SimpleToadletServer.java
- src/freenet/clients/http/WelcomeToadlet.java
Without those no web interface can give a good first time impression.
And the initial speed of Freenet is much better than 10 years ago.
Also this makes the bookmarks load faster when people click them.
> enable activelinks by default

- src/freenet/node/NodeClientCore.java
- src/freenet/pluginmanager/PluginAlreadyLoaded.java
- src/freenet/pluginmanager/PluginDownLoader.java
- src/freenet/pluginmanager/PluginDownLoaderFile.java
- src/freenet/pluginmanager/PluginDownLoaderFreenet.java
- src/freenet/pluginmanager/PluginDownLoaderOfficialFreenet.java
- src/freenet/pluginmanager/PluginDownLoaderURL.java
- src/freenet/pluginmanager/PluginManager.java
Lots of clean ups and refactorings in one of `PluginManager`’s most ugly methods.
> Plugin manager clean up

- NEWS.md
- src/freenet/clients/http/DarknetConnectionsToadlet.java
- src/freenet/l10n/freenet.l10n.en.properties
instead of hiding the n2ns in a dropdown list
> add "send confidential message" button to friends page

- src/freenet/client/filter/DataFilterException.java
- src/freenet/client/filter/OggBitstreamFilter.java
- src/freenet/client/filter/TheoraBitstreamFilter.java
- src/freenet/client/filter/TheoraPacketFilter.java
I hope these changes will allow to play videos.
> Ogg - Theora fixes

- src/freenet/clients/http/bookmark/BookmarkManager.java
Bug: Freenet failed to start when the bookmarks.dat file was missing. This fixes the NPE.
> Survive missing bookmarks

- src/freenet/keys/Key.java
- src/freenet/support/compress/AbstractCompressor.java
- src/freenet/support/compress/Bzip2Compressor.java
- src/freenet/support/compress/CompressionRatioRuntimeException.java
- src/freenet/support/compress/Compressor.java
- src/freenet/support/compress/GzipCompressor.java
- src/freenet/support/compress/NewLZMACompressor.java
- test/freenet/support/compress/Bzip2CompressorTest.java
- test/freenet/support/compress/GzipCompressorTest.java
- test/freenet/support/compress/NewLzmaCompressorTest.java
> CompressionRatioException restriction

- src/freenet/client/filter/CSSTokenizerFilter.java
Resolve merge conflicts on https://github.com/freenet/fred/pull/456
> Cleanup minor css filter rebase

- src/freenet/client/filter/BMPFilter.java
- src/freenet/client/filter/CSSReadFilter.java
- src/freenet/client/filter/ContentDataFilter.java
- src/freenet/client/filter/ContentFilter.java
- src/freenet/client/filter/FlacFilter.java
- src/freenet/client/filter/GIFFilter.java
- src/freenet/client/filter/HTMLFilter.java
- src/freenet/client/filter/JPEGFilter.java
- src/freenet/client/filter/M3UFilter.java
- src/freenet/client/filter/MP3Filter.java
- src/freenet/client/filter/OggFilter.java
- src/freenet/client/filter/PNGFilter.java
This keeps compatibility with plugins using the readFilter.
> provide default implementation for the previous readFilter interface

- src/freenet/clients/http/ToadletContextImpl.java
- src/freenet/clients/http/staticfiles/js/m3u-player.js
Compatibiity fixes to work on mobile browsers.
> m3u compability for mobile devices

- src/freenet/clients/http/wizardsteps/BANDWIDTH_RATE.java
> Increase default upload bandwidth if none detected to 32KiB/s

- src/freenet/client/filter/GenericReadFilterCallback.java
- src/freenet/clients/http/ImageCreatorToadlet.java
- test/freenet/clients/http/ImageCreatorToadletTest.java
This page looks like image placeholder generator for freesites. If so, then it is worth to be able to use this URL from the site.
> Allow ImageCreator url from freesites

- src/freenet/node/PeerManager.java
Signed-off-by: Arne Babenhauserheide <arne_bab@web.de>
> fix FOAFMitigationHack

- NEWS.md
this is the plan, I hope we’ll get all the points reviewed
> prepare news for 1495

- src/freenet/client/filter/ElementInfo.java
Signed-off-by: Arne Babenhauserheide <arne_bab@web.de>
(Written by Spider-Admin, reviewed by Arne)
> add support for CSS selector focus-within.

- test/freenet/support/FieldTrimSecondTest.java
bug: https://freenet.mantishub.io/view.php?id=7184
> fix unit test for bandwidth field parsing

- src/freenet/client/HighLevelSimpleClientImpl.java
bugfix, @Bombe can you have a look?
> Client getter honor max size argument

- src/freenet/clients/http/templates/first-time-wizard.html
The first is vitally important in countries with Asian writing systems! The second is important for people used to command their phones by voice; essential warning for the android app.
> add warnings about IME and voice recognition to the new wizard.

- test/freenet/support/compress/GzipCompressorTest.java
Fix compression result comparison in the GzipCompressorTest for newer JDKs
----
Newer JDKs changed how GZIP OS(Operating System) member header value is assigned. Test data value in the test uses fixed constant, which differs from value assigned by newer JDKs. This caused the tests to fail on newer JDKs like 17 and 19.
The solution for this was initially described in the bug comments in: https://freenet.mantishub.io/view.php?id=7176
This change just assigns a fixed value to the GZIP OS member header byte to the compressed data, which becomes same as in the test data.
Also some minor test improvements are included.
As a result, project now is able to build with JDK 17 and 19
Signed-off-by: Veniamin Fernandes <veniamin.fernandes@proton.me>
> Fix compression result comparison in the GzipCompressorTest for newer JDKs

- test/freenet/client/filter/ContentFilterTest.java
This is an embarrassing one … it looks like our debian package build doesn’t run the tests yet.
> Fix merge error.

- src/freenet/clients/fcp/GetFailedMessage.java
- test/freenet/clients/fcp/GetFailedMessageTest.java
(bug reported by oishii@e-FUmCyxfF9D… on FMS)
> Add missing Global flag to GetFailed FCP message. Thanks to oishii!

- src/freenet/client/filter/PNGFilter.java
- src/freenet/io/xfer/PartiallyReceivedBulk.java
- src/freenet/node/IPDetectorPluginManager.java
- src/freenet/node/PeerManager.java
- src/freenet/node/TextModeClientInterface.java
Break out of the loop once the condition is met
> break early when condition is met

- src/freenet/client/filter/HTMLFilter.java
https://developer.mozilla.org/en-US/docs/Web/HTML/Viewport_meta_tag
This shouldn't be evil, could make sites mobile friendly.
> Allow meta viewport

- NEWS.md
It’s actually quite a huge change.
> Update NEWS for 1498

- src/freenet/pluginmanager/PluginManager.java
This is just a band-aid. We may want to copy the plugin list instead.
> Resilience against plugin list exception

- src/freenet/clients/http/FProxyToadlet.java
Forgot to add image/webp here.
> Add image/webp as prefetch allowed types

- src/freenet/client/DefaultMIMETypes.java
These new file formats should have a MIME type here
> Add new MIME types image/avif, heic, heif

- src/freenet/client/filter/CSSTokenizerFilter.java
- test/freenet/client/filter/CSSParserTest.java
Add text-combine-upright,text-decoration-thickness.
Maybe more to come, until no more CSS properties need to be updated, or until someone can start a review.
> Update CSS filter

- src/freenet/clients/http/LocalFileBrowserToadlet.java
- src/freenet/clients/http/staticfiles/themes/winterfacey/theme.css
Fixes https://freenet.mantishub.io/view.php?id=1956
> Human-readable file size formatting in directory listing

- README.md
Show GitHub Actions status using shields.io
> update README badge for build status

- src/freenet/client/filter/CSSTokenizerFilter.java
There was a typo, wave is not a valid text-decoration value.
> Fix typo in text-decoration filter

- src/freenet/client/filter/CSSTokenizerFilter.java
- test/freenet/client/filter/CSSParserTest.java
Add CSS properties:
* border-block-end-color
* border-block-end-style
* border-block-end-width
* border-block-start-color
* border-block-start-style
* border-block-start-width
* border-end-end-radius
* border-end-start-radius
* border-inline-end-color
* border-inline-end-style
* border-inline-end-width
* border-inline-start-color
* border-inline-start-style
* border-inline-start-width
* border-start-end-radius
* border-start-start-radius
Also removed duplicated filter code for border properties.
> Add CSS properties border-block/inline-start/end-color/style/width, border-end/start-end/start-radius

- src/freenet/support/io/FileUtil.java
As we've dropped support for Java 5 for a while now, we can access these methods without reflection.
> Don't use reflection for updating file attributes

- src/freenet/crypt/CryptoKey.java
- src/freenet/crypt/DSAPublicKey.java
Unlikely to lead to any real-world performance gains as this code is seldom used, but more the reason to just get a fresh digest when needed.
> Do not synchronize on global variable in CryptoKey.fingerprint

- src/freenet/node/CHKInsertHandler.java
- src/freenet/node/NodeStats.java
- src/freenet/node/RequestHandler.java
- src/freenet/node/SSKInsertHandler.java
- src/freenet/node/UIDTag.java
Feature has been disabled since 2013 (see commit 85642664) due to not working and has not been worked on since; remove the code.
> Remove remaining code paths for disabled slow-down sending

- src/freenet/client/ArchiveManager.java
- src/freenet/client/async/ClientContext.java
- src/freenet/client/async/ClientRequestScheduler.java
- src/freenet/client/async/ClientRequestSelector.java
- src/freenet/client/async/InsertCompressor.java
- src/freenet/client/async/SingleBlockInserter.java
- src/freenet/client/async/USKManager.java
- src/freenet/client/async/USKRetriever.java
- src/freenet/node/useralerts/UserAlertManager.java
With every test added, I’ll probably find more member fields that need accessors. 🙂
> ♻️ Use accessor for NodeClientCore.mainExecutor

- src/freenet/clients/http/QueueToadlet.java
The regression came in in a merge between different refactoring PRs.
> Fix regression: compress parameter was inverted on upload. Thanks to NewOne@umLZL for investigating!

- src/freenet/clients/http/WelcomeToadlet.java
- src/freenet/l10n/freenet.l10n.en.properties
Context is https://floss.social/@Freenet/114498726482777333
> Add info how to disable autostart in GNU Linux

- src/freenet/client/filter/PNGFilter.java
- test/freenet/client/filter/PNGFilterTest.java
- test/freenet/test/PngUtil.java
New HDR chunks just became W3C Recommendation. From the W3C documentation there isn't any URLs in them, only numbers.
> Add support for new HDR chunks in PNG
